prometheus/client_golang

examples/random/main.go, examples/simple/main.go
I intentionally left out the Makefile infrastructure that we had
previously for this, as it's not strictly needed and adds
complexity/maintenance burden.
=> Re-add some simple example binaries.

examples/random/main.go
Have different RPC rates for the three services and vary them according
to a diurnal period.
=> Make random example more interesting.

AUTHORS.md, CONTRIBUTING.md, LICENSE, NOTICE, README.md
=> License cleanup

prometheus/counter.go, prometheus/counter_test.go
=> Add const labels to counter.

prometheus/README.md
Extra '}'  + corresponding gofmt
=> Fix document

prometheus/registry.go
=> Fix for Histogram in registry.writePB

model/metric.go, model/metric_test.go
=> Fix pointer receiver in COWMetric.Set().

prometheus/examples_test.go, prometheus/histogram.go, prometheus/summary.go
Fixes https://github.com/prometheus/client_golang/issues/114
@oliver006 @brian-brazil @juliusv and whoever else is interested... :)
=> Make it possible to create constant summaries and histograms from static values.

prometheus/histogram.go, prometheus/value.go
=> Ensure alignment of struct members used in sync.atomic functions.

model/labelname.go, prometheus/desc.go
As discussed @fabxc .
This will be used in the Pushgateway, too.
=> Make LabelNameRE public.

model/metric.go, prometheus/registry.go, prometheus/registry_test.go, text/create.go, text/parse.go
- Clarify documentation about sorting requirements.
- Add missing histogram support in consistency check.
- Add label sorting to consistency check.
- Improve error messages when reporting a metric.
(Previously, the metric name was not printed.)
@fabxc This is a fallout of my Pushgateway work.
=> Fix a number of minor things.

model/labelname.go
This is related to prometheus/prometheus#786
=> Rename ExporterLabelPrefix to ExportedLabelPrefix.

model/labelname.go
For https://github.com/prometheus/prometheus/pull/934
@juliusv
=> Add ParamLabelPrefix for relabelling of query params.

model/labelname.go
As discussed in https://github.com/prometheus/prometheus/issues/910#issuecomment-128305407
=> Add scheme as label to allow relabelling in discovery

model/labelname.go
=> Reserve a label prefix for use for temporary relabeling.

prometheus/registry.go
=> Move from client_golang/text to common/expfmt

api/prometheus/api.go
=> Use ctxhttp package for cancelable requests

prometheus/go_collector.go
This is still a work in progress. 
Is this along the lines for what you had in mind for #96 @beorn7? I'm new to prometheus and this client library, feedback is greatly appreciated.
=> memstats collection

prometheus/desc.go, prometheus/fnv.go, prometheus/registry.go
Just to finish the job.  Should fix #183.
For @beorn7 again?
=> use local fnv hash everywhere

api/prometheus/api.go
Same problem
https://github.com/prometheus/prometheus_cli/pull/12
=> Support external-url

prometheus/vec.go, prometheus/vec_test.go
=> Add "real" collision to MetricVec tests

README.md, api/prometheus/api.go, api/prometheus/api_test.go, prometheus/desc.go, prometheus/examples_test.go, prometheus/expvar_collector_test.go, prometheus/push/examples_test.go, prometheus/registry.go, prometheus/summary_test.go, prometheus/vec_test.go
FIxes #237.
With :heart: , for @grobie
=> Add goreport card and remove warnings where feasible

prometheus/histogram_test.go
=> Adding a test for non-monotonic buckets

prometheus/process_collector.go, prometheus/process_collector_test.go
Fixes #252.
@beorn7 @brian-brazil @oliver006
=> Fix namespace of process collector metrics

prometheus/graphite/bridge.go, prometheus/graphite/bridge_test.go
@beorn7 first pass at writing a graphite bridge. Let's talk about this when you have a chance. I have several questions written in comments, and I'm sure you'll have more to say too.
This PR addresses #197
=> Graphite bridge

prometheus/graphite/bridge.go
Adjustments as needed by https://github.com/prometheus/common/pull/73
@juliusv
=> graphite: Adjust ExtractSamples call to new interface

prometheus/http.go
=> InstrumentHandler: Document issues with HTTP/2

prometheus/doc.go
My editor automatically made these changes to line-breaks and fixed indentation. Let me know if I should remove them.
=> Document graphite bridge

prometheus/promhttp/instrument_client.go, prometheus/promhttp/instrument_client_1_8.go, prometheus/promhttp/instrument_server.go, prometheus/push/example_add_from_gatherer_test.go, prometheus/timer.go
“Fixes” #280 .
@grobie @AlekSi @brian-brazil
=> Document the use of Go1.9+ for monotonic time where applicable

prometheus/go_collector.go, prometheus/go_collector_test.go
Fixes issue https://github.com/prometheus/client_golang/issues/328
=> Add new default metric go_info

prometheus/doc.go
`DefaultRegistry` no longer exists as of a6321dd0b.
/cc @beorn7
=> Correct DefaultRegistry to DefaultRegisterer

prometheus/registry.go
Attempt to fix #369. This needs to be tested with one of those scenarios as in https://github.com/prometheus/statsd_exporter/issues/76 .
@grobie @brian-brazil
=> Create goroutines adaptively during metrics gathering

prometheus/promhttp/delegator.go, prometheus/promhttp/delegator_1_8.go, prometheus/promhttp/instrument_server_test.go
@tsandall More bug fixes of the same kind as yours. And a test…
=> Fix more interface upgrade bugs

prometheus/process_collector.go, prometheus/registry.go
@maxtar
To address the documentation issue raised in #376 .
=> Document that the process collector only works on Linux

prometheus/http.go, prometheus/promhttp/http.go, prometheus/promhttp/http_test.go
See https://github.com/prometheus/client_golang/issues/316 for details.
Fixes #316 . @grobie @brian-brazil
=> Provide an InstrumentedHandler

prometheus/promhttp/http.go, prometheus/promhttp/http_test.go
=> promhttp: Introduce limit for connections in flight and timeout

prometheus/vec.go
=> Fix unprotected write in metricMap

api/client_test.go, prometheus/expvar_collector_test.go, prometheus/go_collector.go, prometheus/http.go, prometheus/http_test.go, prometheus/metric.go, prometheus/process_collector.go, prometheus/process_collector_test.go, prometheus/promhttp/http.go, prometheus/promhttp/http_test.go, prometheus/push/push.go, prometheus/registry.go, prometheus/value.go
@beorn7 Please review.
Feel free to cherry-pick if you don't agree with all commits.
=> Cleanups and fixes

MAINTAINERS.md
=> Make Krasi the maintainer for the HTTP API client

prometheus/graphite/bridge.go, prometheus/graphite/bridge_test.go
Refer to #418.
Signed-off-by: neeral <neeral@users.noreply.github.com>
=> Do not sanitize prefix in Graphite bridge

prometheus/http.go
go routine to goroutine
Signed-off-by: Dalei Li <dalei.li@icloud.com>
=> go routine to goroutine

prometheus/testutil/testutil.go, prometheus/testutil/testutil_test.go
@grobie 
This concludes #58. Note that more test utils will be added as per #230 with the improved type stucture planned for v0.10.
=> Add a single-value extractor and general package doc

prometheus/collector.go, prometheus/collector_test.go
=> Add a DescribeByCollect helper

prometheus/collector.go, prometheus/example_clustermanager_test.go, prometheus/metric.go, prometheus/registry.go, prometheus/value.go, prometheus/wrap.go, prometheus/wrap_test.go
Essentially middleware for Registerers!
@juliusv @fabxc @brancz you all requested this feature. Sorry for the long delay.
@stuartnelson3 as my local main reviewer while @grobie is on vacations.
=> Wrappable registerers

prometheus/histogram.go
=> Ensure 64bit alignment on 32bit platforms for histograms

prometheus/registry_test.go
@stuartnelson3 very minor thing I stumbled upon when chasing real bugs...
=> Adjust TestRegisterWithOrGet to the present

prometheus/promhttp/instrument_server.go
This pull request aims to close issue #387. As this is part of version 0.10.0, should it be merge in master or in another branch? 
Signed-off-by: glefloch <glfloch@gmail.com>
=> Sanitize http method to uppercase

prometheus/http.go, prometheus/promhttp/http.go, prometheus/promhttp/http_test.go, prometheus/registry_test.go
@glefloch Here the promised joint PR.
=> Use gzip from a pool and stream while encoding metrics

prometheus/wrap_test.go
@simonpasquier as discussed in #501 .
=> Remove accidental gogo/protobuf import

prometheus/desc.go
Fixes #504.
Signed-off-by: Peter Jausovec <peter.jausovec@oracle.com>
=> Update the label is not valid error message to include the fqName

Makefile.common
=> Propagate Makefile.common fix

prometheus/timer.go
=> Return observed duration from Timer.ObserveDuration

prometheus/summary.go
This wording isn't necessary, IMHO.
=> prometheus: reword comment to avoid cursing

prometheus/promhttp/instrument_client_1_8_test.go
Signed-off-by: Kasey Klipsch <junk@klipsch.net>
=> fix client trace examples to actually capture metrics

api/prometheus/v1/api.go
Add alerts endpoint to API client. The alerts endpoint returns a list of all active alerts.
/cc @krasi-georgiev 
Signed-off-by: Roald Nefs <info@roaldnefs.com>
=> Add alerts endpoint to API client

prometheus/promhttp/instrument_client_test.go
=> Remove remaining traces of pre-go-1.8 handling

prometheus/go_collector_test.go
Related to #573 (but only partially fixes it).
@simonpasquier @krasi-georgiev This is the fix I want to get in before cutting v0.9..3 in #579 .
=> Fix race in TestGoCollectorMemStats

prometheus/promhttp/instrument_client.go, prometheus/promhttp/instrument_client_test.go
Fixes #580
@shturec does this do the trick?
=> Make use of pre-existing context in InstrumentRoundTripperTrace

api/prometheus/v1/api.go, api/prometheus/v1/api_test.go
a follow-up on https://github.com/prometheus/prometheus/pull/5582
=> /api/v1/rules: alert value as string

api/prometheus/v1/api.go, api/prometheus/v1/api_test.go
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>
fixes: https://github.com/prometheus/client_golang/issues/587
=> encapsulate target metadata api

api/prometheus/v1/api.go, api/prometheus/v1/api_test.go
Added upstream in https://github.com/prometheus/prometheus/pull/5673
=> Add Warnings to LabelValues and LabelNames

MAINTAINERS.md
GH handle position follows the schema in prometheus/prometheus.
=> Update beorn's e-mail and add GH handles

prometheus/registry.go
Small fix in the documentation.
@beorn7
=> Fix typo in documentation.

prometheus/push/push.go
Fix https://github.com/prometheus/client_golang/issues/650
@beorn7
=> Fix check status code

prometheus/go_collector_test.go
This is not a great solution, but it's also hard to test for this
moving target.
Fixes #653 .
=> Unflake TestGoCollectorGoroutines

prometheus/histogram.go, prometheus/summary.go
`gofmt -s` taught me that this is possible.
@cstyan
=> Simplify code

README.md
=> Add more precise Go version requirements.

MAINTAINERS.md
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>
=> remove Krasi from the maintainers.

prometheus/histogram.go
* https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels,-not-static-scraped-labels
---> 
* https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels
=> Fix link to writing exporters guide

.circleci/config.yml, .travis.yml
I have also finally added the webhook to activate CircleCI. Let's see how it goes.
=> Add Go 1.14

api/prometheus/v1/api.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
=> Fix time parameter propagation in labels API

prometheus/gauge_test.go, prometheus/histogram_test.go, prometheus/summary_test.go
See https://github.com/golang/go/issues/32479
Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>
=> fix tests warning about string(int) type conversions

prometheus/go_collector.go
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Update collector comment about GC stop-the-world

.circleci/config.yml
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Support go 1.15

api/prometheus/v1/example_test.go, go.sum
Found some users looking for this, so adding to help others :hugs: 
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Added example api code showing how to add auth tokens and user agents to prom client.

go.mod, go.sum
This picks up https://github.com/prometheus/procfs/pull/325
=> Bump prometheus/procfs to 0.3.0 to fix building on riscv64

api/prometheus/v1/api.go, api/prometheus/v1/api_test.go
https://github.com/prometheus/prometheus/pull/6503/files added new fields to the API that the client wasn't using. I've updated it now.
=> Add newer fields to Rules API

prometheus/collectors/dbstats_collector.go, prometheus/collectors/dbstats_collector_go115.go, prometheus/collectors/dbstats_collector_pre_go115.go
@johejo here is what I meant. Would you mind reviewing this?
=> Make dbStatsCollector more DRY

README.md, prometheus/README.md
Update to new locations
* Switch to CircleCI build badge.
* Use new pkg.go.dev for docs.
Signed-off-by: SuperQ <superq@gmail.com>
=> Update status badgets

prometheus/metric_test.go
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Fixed lint warning.

.github/stale.yml
The thresholds are pretty generous. This shouldn't create any pressure on contributors.
On top of that, I have excluded issues with a milestone attached.
=> Add statebot config

api/prometheus/v1/api.go
Fixes #1036
Signed-off-by: Joseph Woodward <joseph.woodward@xeuse.com>
=> Document WithTimeout option for Query/QueryRange

.github/settings.yml
Add a GitHub settings control yaml to manage branch protection for the
Go versions.
Signed-off-by: SuperQ <superq@gmail.com>
=> Add GitHub settings

examples/random/main.go
=> Fix typo in doc comment

README.md
=> Add missing tick "`" in README

MAINTAINERS.md
(we agreed on it offline with @kakkoyun and @beorn7)
=> Added Arthur as an official maintainer of client_golang 🤗🔥

prometheus/gen_go_collector_metrics_set.go
=> This way the import is more readable

prometheus/registry.go
Change Registry functions check label names dump code style; use two if replace if/else if /else statement； @ArthurSens @bwplotka @kakkoyun
=> improved code more clean

.github/pull-request-template.md, .github/workflows/pr-auto-label.yml
Add functionality to remove redundant PR labels when the PR labeler workflow works (added in #1518).
/kind release-note-none
```release-note
NONE
```
=> Fix: Auto label PRs #1518

prometheus/process_collector.go, prometheus/process_collector_other.go, prometheus/process_collector_test.go
On systems with procfs, collect the count of bytes received/transmitted of the process.
/kind enhancement
```release-note
process collector: on systems with procfs report the count of bytes received/transmitted.
```
=> process_collector: collect received/transmitted bytes

CHANGELOG.md
As a preparation for the release
=> Add changelog entry for 1.20.3

examples/customlabels/main.go
Fixes: https://github.com/prometheus/client_golang/issues/1585, tested in local. @bwplotka @ArthurSens @kakkoyun
=> examples: Add custom labels example

MAINTAINERS.md
=> Add Arianna as maintainer 💪

RELEASE.md
Add example PR links to RELEASE.md
=> chore(docs): Add links for the upstream PRs

.github/dependabot.yml
Remove Go modules that have been removed.
=> Cleanup dependabot config

prometheus/promhttp/http.go
Fix typo on function documentation.
=> Fix doc typo
