prometheus/registry.go

One line syntactic change with no semantic effects.

Remove a Go 1.4ism to allow compilation under Go 1.3.

---

prometheus/collector.go
prometheus/desc.go
prometheus/example_selfcollector_test.go
prometheus/examples_test.go
prometheus/expvar.go
prometheus/go_collector_test.go
prometheus/metric.go
prometheus/process_collector.go
prometheus/registry.go
prometheus/summary.go
prometheus/value.go

@juliusv @grobie @xla 
Both are interface changes I want to get in before public
announcement. They only break rare usage cases, and are always easy to
fix, but still we want to avoid breaking changes after a wider
announcement of the project.
The change of Register() simply removes the return of the Collector,
which nobody was using in practice. It was just bloating the call
syntax. Note that this is different from RegisterOrGet(), which is
used at various occasions where you want to register something that
might or might not be registered already, but if it is, you want the
previously registered Collector back (because that's the relevant
one).
WRT error reporting: I first tried the obvious way of letting the
Collector methods Describe() and Collect() return error. However, I
had to …

Allow error reporting during metrics collection and simplify Register().

---

model/samplevalue.go
model/timestamp.go

This forces a float format without exponent that uses the minimum number
of digits necessary to display a given sample value.

Better sample value string formatting.

---

prometheus/registry.go

The RLock already needs to be acquired when reading r.dimHashesByName.
This fixes https://github.com/prometheus/client_golang/issues/61
@beorn7 @stapelberg

Fix race condition in writePB().

---

prometheus/counter_test.go
prometheus/gauge_test.go
prometheus/value.go

@juliusv @brian-brazil Rejoice!
This is accomplished by using the functions from the atomic packages
instead of a mutex.
benchmark                                      old ns/op     new ns/op     delta
BenchmarkGaugeNoLabels-2                       118           9.40          -92.03%
BenchmarkGaugeNoLabels                         117           9.38          -91.98%
BenchmarkGaugeNoLabels-4                       117           9.40          -91.97%
BenchmarkCounterNoLabels-2                     137           16.8          -87.74%
BenchmarkCounterNoLabels                       136           16.8          -87.65%
BenchmarkCounterNoLabels-4                     136           16.8          -87.65%
BenchmarkGaugeWithLabelValues-4                400           279           -30.25% …

Improve Gauge and Counter performance.

---

prometheus/process_collector.go
prometheus/process_collector_test.go

If a given pidFn for a process collector can't determine the pid, this
had to be signaled with an invalid pid so far (pid <= 0). In order to
make the error interface clearer for users, this change introduces an
explicit error parameter.
As requested by @juliusv.
@brian-brazil 
---
I'll handle any possible merge conflict errors depending whether #65 or this change will be merged first.

Use clear error interface for process pidFn

---

prometheus/process_collector.go
prometheus/process_collector_procfs.go
prometheus/process_collector_rest.go

The procfs package has a cgo dependency (necessary to calculate system
times). As procfs is not available under windows, darwin and supposely
all newer BSD systems, this change removes the procfs dependency on these
systems.
This will enable cross compilation for linux->darwin again.
@juliusv @beorn7 @discordianfish

Remove dependency on procfs/cgo in non-procfs systems

---

prometheus/process_collector_procfs.go
prometheus/process_collector_rest.go

This makes it possible to explicitly disable the CGO dependency.
Right now I need this to cross-compile prometheus for raspberry pi. Go disables CGO by default if doing cross compiles. With this change you can cross compile prometheus as easy as:
GOARCH=arm go build -tags nocgo
/cc @grobie

Add 'nocgo' tag to remove cgo dependency on build

---

model/timestamp.go

The latter is to eradicate the various MaxInt64 and MinInt64 in the
codebase.
@juliusv

Remove obsolete comment and add Earliest and Latest timestamp.

---

prometheus/process_collector_procfs.go

As it is expected that the process collector can fail under certain
conditions (proc information for a process only readable by root or
other user for example) and as there is currently no option to configure
the error behavior of the client, this change reverts the error
reporting introduced in 159e96f. This effectively means that errors are
simply ignored and there won't be any samples for the process_* metrics
in case of an error.
Once a user can control how to behave in case of errors returned by
collectors, this change should probably be reverted again.
@beorn7 @juliusv @brian-brazil

Handle process collector errors gracefully

---

extraction/metricfamilyprocessor.go
extraction/metricfamilyprocessor_test.go
text/create.go
text/create_test.go
text/parse.go
text/parse_test.go

This does not include a histogram metric usable from the go client.
See https://docs.google.com/document/d/1uSenXRDjDaJLV3qnSD09GqgPdEEDPjER0mVsnGaCYF0/edit#
Make format did a few changes too.
@beorn7 @juliusv

Add support for histograms to parsers, extraction and creation.

---

model/metric.go
model/metric_test.go

Also, add a test to expose
https://github.com/prometheus/client_golang/issues/74 .
benchmark           old ns/op     new ns/op     delta
BenchmarkMetric     7034          6272          -10.83%
benchmark           old allocs     new allocs     delta
BenchmarkMetric     52             32             -38.46%
benchmark           old bytes     new bytes     delta
BenchmarkMetric     1976          1800          -8.91%
@juliusv

Reduce allocations during fingerprinting.

---

prometheus/desc.go
prometheus/example_selfcollector_test.go
prometheus/examples_test.go
prometheus/registry.go
prometheus/registry_test.go
prometheus/summary.go
prometheus/value.go
text/create_test.go
text/parse.go
text/parse_test.go
text/proto.go

The Golang protocol buffer library has now moved to GitHub:
https://github.com/golang/protobuf
Although "go get"-ing the old package name still works, moving
everything to the new one will make vendoring cleaner.
See also https://github.com/matttproud/golang_protobuf_extensions/pull/7

Update protobuf library package name.

---

extraction/metricfamilyprocessor.go
model/labelname.go
prometheus/benchmark_test.go
prometheus/counter.go
prometheus/examples_test.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/http.go
prometheus/registry.go
prometheus/summary.go
text/create.go
text/create_test.go
text/parse.go

@juliusv See commit descriptions for details.

Histograms for the exposition library.

---

prometheus/histogram.go

With the usual number of buckets, this doesn't really make a
difference, but it should scale...
@juliusv  @brian-brazil

Use binary search to pick bucket.

---

examples/random/main.go

Add a histogram to the random example.

---

_vendor/perks/MANIFEST
_vendor/perks/quantile/example_test.go
_vendor/perks/quantile/stream_test.go

@juliusv  Also have to do this now...

Update vendoring of beorn7/perks.

---

model/metric.go
model/metric_test.go
model/signature.go
model/signature_test.go
model/timestamp.go

This fixes https://github.com/prometheus/client_golang/issues/74 .
IT CHANGES THE FINGERPRINTING AND THEREFORE INVALIDATES EACH AND EVERY
PERSISTED FINGERPRINT (I.E. YOU HAVE TO WIPE THE STORAGE TO USE THIS).
This commit removes the LabelValuesToSignature function as it is used
nowhere (and broken in the way it is implemented right now).
Also, remove one more golint warning.
@juliusv

Unify fingerprinting aka signature calculation.

---

Makefile
model/signature.go
model/signature_test.go

sync.Pool is after all faster than the home-made free list. Especially
under contention. To prove that, this commit also adds a benchmark for
concurrent fingerprint calculation.
Benchmark results:
(Run with -cpu=1,2,4. x-y -> x goroutines with GOMAXPROCS=y.)
benchmark                                     old ns/op     new ns/op     delta
BenchmarkMetricToFingerprintTripleConc4-4     320           138           -56.88%
BenchmarkMetricToFingerprintTripleConc8-4     314           141           -55.10%
BenchmarkMetricToFingerprintTripleConc4-2     344           264           -23.26%
BenchmarkMetricToFingerprintTripleConc2-4     331           256           -22.66%
BenchmarkMetricToFingerprintTripleConc8-2     338           263           -22.19%
BenchmarkMetricToFingerprintTripleConc1-4     599 …

Switch to sync.Pool.

---

Godeps/_workspace/src/github.com/beorn7/perks/README.md
Godeps/_workspace/src/github.com/golang/protobuf/LICENSE
Godeps/_workspace/src/github.com/matttproud/golang_protobuf_extensions/LICENSE

As it looks, `godep update ...` will preserve the files.
Obviously, if you blow away everything and run a `godep save ...` from
scratch, those files will be missing again. A `godep save` to add new
dependencies without blowing away the `Godeps` directory should work
fine, though.
@juliusv @TheTincho

Add licenses of vendored code left out by godep.

---

README.md
prometheus/summary.go
prometheus/summary_test.go

@juliusv @grobie @brian-brazil

Fix two bugs (see commit descriptions).

---

prometheus/examples_test.go
prometheus/push.go
prometheus/registry.go

Move all Pushgateway related top-level functions to push.go.
@brian-brazil @juliusv This fixes https://github.com/prometheus/client_golang/issues/98 and contributes to https://github.com/prometheus/pushgateway/issues/27 .

Add functions to push individual collectors to a Pushgateway.

---

model/labelname.go

Some constants being used in the retrieval changes. As these are only additions we don't have to sync merging.

Add constants for instance/address labels and hidden prefix.

---

prometheus/go_collector.go
prometheus/go_collector_test.go

This adds basic garbage collections stats to the metrics that are exported by default by the golang client.

Add garbage collection stats

---

model/metric.go
model/metric_test.go
model/sample_test.go
model/signature.go
model/signature_test.go

@juliusv These are the fixes we need in client_golang. prometheus/prometheus code that uses these fixes needs to be changed to not change the fingerprint used in storage.
(Separate PR imminent.)

Fingerprinting fixes in client_golang

---

prometheus/go_collector.go
text/testdata/text

The decision was made to use the language name for language specific
metrics, so go_goroutines is the right names similar to
go_gc_duration_seconds.
Fixes #121.

Rename process_goroutines to go_goroutines

---

prometheus/http.go

`InstrumentHandler` provides proxy object over given `http.ResponseWriter` - `responseWriterDelegator` that only implements the bare minimum required of an `http.ResponseWriter` and doesn’t implement any interface upgrades (`http.Flusher`, `http.Hijacker`, etc.). One example of negative side-effect of this is decreased performance of `http.FileServer` handler after instrumentation.
This PR fixes it by providing `fancyResponseWriterDelegator` with all the fancy bells and whistles if standard library `http.ResponseWriter` is detected. More info [here](https://avtok.com/2014/11/05/interface-upgrades.html#the-proxy-problem).
I also switched `responseWriterDelegator.written` to int64 (to allow responses greater than 4GB) in different commit. If you prefer two different PRs or one PR with …

Solve "The Proxy Problem" of http.InstrumentHandler

---

README.md

The prometheus link in the README is broken - there is no page at www.prometheus.io (it's at promethius.io - I guess they didn't set up a redirect). @beorn7

Remove www subdomain from Prometheus link.

---

prometheus/examples_test.go
prometheus/vec.go

This fixes https://github.com/prometheus/client_golang/issues/119.
@fabxc 
@discordianfish @juliusv for your information.

Document the possibility to create "empty" metrics in a metric vector.

---

prometheus/summary.go

I ended up following the source to the quantile package https://godoc.org/github.com/prometheus/client_golang/Godeps/_workspace/src/github.com/beorn7/perks/quantile#NewTargeted to understand the meaning of `Objectives`, so some kind of documentation change would be appreciated. Maybe this works?

More explicit documentation of SummaryOpts.Objectives.

---

Makefile

Using tabs to align things has the downside that people who have set the
tabstop to be of a different lenght than the orignial author's run the
risk of not having the alignment stay. In the current Makefile before
this change people with tabstop of 4 do not see the equals line up.

Use spaces instead of tabs to align equals (=)

---

model/signature_test.go

Success of this test was runtime dependent and did not validate
the implementation logic itself.
@brian-brazil

Remove runtime-dependent test.

---

model/signature_test.go

It even stays at logging an error. But now it is not in the testing path which should succeed without exception if the code compiles.
@grobie

Turn allocation test into a benchmark.

---

api/prometheus/api.go
api/prometheus/api_test.go

Implementation of an API package. It supports the querying endpoints of HTTP API v1 – the other ones can be added as needed.
I would consider this beta status as it uses `common/model` which we haven't rolled out to client_golang or prometheus in general. It's a good chance to test it out though, as it is independent in this API package.
@juliusv

Add initial HTTP API v1 package

---

prometheus/desc.go
prometheus/histogram.go
prometheus/metric.go
prometheus/registry.go
prometheus/summary.go

This removes client_golang/model as a direct dependency from the instrumentation.
It's still a dependency via the text parser, however.
It was only used for constants, which are well-specified enough that replicating them is okay.
@brian-brazil @juliusv

Remove client_golang/model als direct dependency

---

prometheus/benchmark_test.go
prometheus/counter.go
prometheus/fnv.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/summary.go
prometheus/untyped.go
prometheus/vec.go
prometheus/vec_test.go

Joint work with @alicebob. @beorn7, you seem to know the vector stuff well?
* Inline the label hashing to remove the need to keep around and lock a shared buffer and hash.
* Try looking up metrics with a read lock before falling back to a write-locked "get or create".
This should improve lock contention issues when using variable labels in a concurrent setting. (We're currently using the hacky https://github.com/realzeitmedia/promvec, which avoids locking altogether.)
The benchmark results look quite good. BenchmarkHandler varies a lot between runs, that delta is not always positive.
```
$ benchcmp old.txt new.txt 
benchmark                                       old ns/op     new ns/op     delta
BenchmarkCounterWithLabelValues-4               462           144           -68.83% …
```

Less locking for metric vectors.

---

prometheus/registry.go

Presently metricSorter is unstable because Less returns "true" instead of "false" when two metrics compare the same.  This means when Collectors emit timestamped metrics in order, this sort will perturb the ordering and result in metrics delivered out-of-order to Prometheus.  This PR fixes the return value for Less.
Since we're going through the trouble of reordering metrics here anyway, explicitly sort by TimestampMs as well.

Make metric sort stable and sort by timestamp

---

prometheus/registry.go

This circumvents the following problem:
• The prometheus client library appends “/metrics/…” to the pushURL.
• When pushURL ends in a trailing slash, the URL becomes e.g.
http://pushgateway.example.com:9091//metrics/…
• The pushgateway will reply with an HTTP 307 status code
(temporary redirect).
• While Go’s net/http client follows redirects by default, it will only
follow HTTP 302 (Found) and HTTP 303 (See Other) redirects for PUT and
POST requests, which the prometheus client library uses.
Hence, when calling e.g.:
prometheus.Push("foo", "bar", "http://pushgateway.example.com:9091/")
…your metrics would not actually get pushed successfully, but rather
you’d see the error message:
2015/11/26 10:59:49 main.go:209: unexpected status code 307 while pushing to http://push...

Strip trailing / from push URL.

---

prometheus/go_collector.go

'^' is the bitwise XOR, and ms.LastGC is in nanoseconds.
For @beorn7 maybe?

fix go_memstats_last_gc_time_seconds division

---

prometheus/process_collector_test.go

This test fails when max_fds is a large value; say 4.5e+06, for example. Change it to match virtual_memory_bytes, which also has to handle large values.

Fix max_fds process collector test

---

prometheus/http.go
prometheus/registry.go

Obvious next step: Fix those issues. (Which I'm already working on.)
@raliste This at least documents what you have run into in #200 .

Document the issues of InstrumentHandler

---

prometheus/doc.go

Sorry to driveby like this. Thought it might be useful to link to the metric types doc somewhere

prometheus/docs: Added a link to the metric types page

---

prometheus/http.go

The line after the first in each bullet point was appearing as
preformatted blocks when viewed as HTML in GoDoc.
E.g.: https://godoc.org/github.com/prometheus/client_golang/prometheus#InstrumentHandler

Fix GoDoc indentation

---

prometheus/registry.go

This enables a little bit more flexibility and less boilerplate for registering many Collectors.
- One-liner `MustRegisterAll(coll1, coll2, coll3, coll4)`
- Spread a slice `MustRegisterAll(collectors...)`

Add *RegisterAll functions with variadic args

---

api/prometheus/api.go

From what I can see, both `Client` and `QueryAPI` are safe for use from multiple goroutines as they don’t modify any state. Let’s document this so that others don’t need to review the source as well :).

api: document goroutine safeness

---

prometheus/counter.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/summary.go
prometheus/untyped.go
prometheus/vec.go
prometheus/vec_test.go

While hash collisions are quite rare, the current state of the client
library carries a risk of merging two separate label values into a
single metric bucket. The effects are near impossible to detect and the
result will be missing or incorrect counters.
This changeset handles hash collisions by falling back to collision
resolution if multiple label values hash to the same value. This works
similar to separate chaining using a slice. Extra storage is minimized
to only the value key slice to that metrics can be differentiated
within a bucket.
In general, the cost of handling collisions is completely minimized
under normal operation. Performance does show slight increases in
certain areas, but these are more likely statistically anomalies. More
importantly, zero allocation behavior for …

metricvec: handle hash collision for labeled metrics

---

prometheus/http.go

Hi
I know that http.go will be deprecated in the future.
But i have just found a goroutine leak in this file. 
A goroutine leak occurs because the goroutine at line [275](https://github.com/prometheus/client_golang/blob/master/prometheus/http.go#L275) never finish when a panic occurred at line [287](https://github.com/prometheus/client_golang/blob/master/prometheus/http.go#L287) .
So i think we should fix it.

Fix goroutine leak

---

prometheus/process_collector.go

This is needed to remove the deprecated Set method from the Counter.
@grobie 
This contributes to #219.

Convert process collector to const metrics

---

prometheus/counter.go
prometheus/http.go
prometheus/http_test.go
prometheus/registry.go
prometheus/registry_test.go

That's the "soft" part of the deprecation: Everything that has been
marked deprecated in v0.8 or earlier and is straight-forward to
replace by a non-deprecated way, is removed here.
Sadly, this does not include the HTTP part. We first need to provide a
replacement for HTTP instrumentation (as planned for v0.8) to then
remove the deprecated parts in v0.9.
@grobie so that you know why I had to do #246 already.
@stuartnelson3 as current partner in crime for this repo.
Reviews from either of you are acceptable...

Remove deprecated features that are esay to replace

---

examples/random/main.go
examples/simple/main.go
prometheus/doc.go

@beorn7 
Enhanced the documentation as discussed on the mailinglist to check the http.ListenAndServe() call for returned errors.
Changed the two examples accordingly.

Documentation enhancement

---

prometheus/desc.go
prometheus/push/push.go

All was a mess, we had duplicates of the REs for label name and metric
names here, and we sometimes used them, sometimes we used those from
common/model.
Now we are consistently using the fast checking functions from common/model.
(Tests for leading colons are included there, see
https://github.com/prometheus/common/pull/66 .)
@stuartnelson3 @grobie @kamalmarhubi

Remove local REs for label and metric names and use fast checks

---

examples/random/main.go
examples/simple/main.go

- Use seconds instead of microseconds.
- Use promhttp.Handler instead of prometheus.Handler
@grobie @iamjarvo

Adjust examples to modern usage

---

prometheus/counter.go
prometheus/gauge.go
prometheus/gauge_test.go
prometheus/untyped.go
prometheus/value.go

- Point from Inc and Dec to Add and Sub in doc comments.
- Deprecate Untyped for direct instrumentation.
- Add a SetToCurrentTime method to Gauge
Note that adding the SetToCurrentTime method is not really following
Go's principle of lean interfaces. However, the Gauge interface is
already quite fat. (The only methods really required are Set and
Add. Everything else could be expressed in terms of those two.) So we
have already quite a few "convenience" methods traditionally, so I
think we should stay consistent here.
The alternatives would be:
- Not support SetToCurrentTime at all (it's only a SHOULD in the
guidelines).
- A top level function `SetToCurrentTime(Gauge)`.
- Just a helper `CurrentTime()` that returns the curent unix time in
seconds as a float (which is pretty verbose using the …

Bring Gauges and Counters in line with client library guidelines

---

prometheus/push/example_add_from_gatherer_test.go
prometheus/push/examples_test.go

@brian-brazil Is this meeting your expectations for a typical batch job?
I used the new SetToCurrentTime method here, and the metrics as suggested.
Note the use of `push.AddFromGathere` instead of just `push.FromGatherer` as discussed earlier.
I find this quite clear and concise. My only concern is that the success time and completion time will be slightly different. (Which ironically is a side effect of the SetToCurrentTime method. If it didn't exist, one would probably set a variable to the current timestamp first and then set both gauges to that value.)

Extend the example for pushing to pushgateway

---

prometheus/go_collector.go

It's not a counter after all.
Also, remove a misleading part of the sys_bytes help string.
@stuartnelson3 
Fixes #229

Make heap_released_bytes a Gauge.

---

examples/random/main.go
prometheus/benchmark_test.go
prometheus/examples_test.go
prometheus/graphite/bridge_test.go
prometheus/http.go
prometheus/http_test.go
prometheus/summary.go
prometheus/summary_test.go

This also updates all tests and examples to use explicitly set
objectives.
In v0.10, DefObjectives will be completely removed, and the default
Summary will have no objectives then.
Fixes #118 
@stuartnelson3

Allow Summaries with empty objectives and deprecate DefObjectives

---

prometheus/go_collector.go
prometheus/go_collector_test.go

@beorn7 I want to add a threads count gauge in the default go collector, but I just make a workaround to pass the unit test, and I am thinking a way to test it.
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

goCollector: add thread count gauge in goCollector

---

prometheus/example_timer_gauge_test.go

The example method is assumed to be used as main() function. As a main()
function doesn't have any return values, the example doesn't compile and
is invalid.
@beorn7

Fix invalid Timer (gauge) example

---

prometheus/go_collector.go

@beorn7 
We would really like to track the `runtime.MemStats.GCCPUFraction` as part of the runtime stats.

Adding GCCPUFraction metric to goCollector

---

prometheus/histogram.go
prometheus/histogram_test.go
prometheus/observer.go
prometheus/promhttp/delegator_1_7.go
prometheus/promhttp/delegator_1_8.go
prometheus/promhttp/http.go
prometheus/promhttp/http_test.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go
prometheus/summary.go
prometheus/summary_test.go
prometheus/timer.go
prometheus/timer_test.go

The main premise is to provide some middleware that a user can compose as s/he wishes, instead of the "all or nothing" approach of the current `InstrumentHandler()` approach.
Things to note:
- This pr makes use of the `Observer` interface, and additionally adds an `ObserverVec` interface.
- The `ObserverVec` interface was discussed with @beorn7 and necessitated a breaking change to `SummaryVec` and `HistogramVec` by changing the return types of their methods for interacting with labels. @beorn7 scanned code usage for this library and saw that while it is a breaking change, in practice he didn't find anyone using methods other than `Observe()` on the return type, which will not break based on this change. @beorn7 can you confirm this?
- The tests fail because we are compiling against …

new handler instrumentation

---

prometheus/promhttp/instrument_client_1_8_test.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go

See commit descriptions.
Fixes #299 .
@stuartnelson3

Improve promhttp middleware

---

prometheus/promhttp/delegator_1_7.go
prometheus/promhttp/delegator_1_8.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go

@beorn7 first stab at writing the "time to writing header" middleware.
Things to note are:
- I've forgone branching between "has the code label" and "doesn't have the code label". They paths are too similar to warrant it IMO.
- As mentioned, this is just based off what I saw in https://github.com/mwitkow/go-httpwares/pull/12. No strong opinions one way or another, but this seemed like a simple way to implement it. I didn't think it necessary to generalize quite like that PR did with a slice of callback functions.

Add time to write header handler middleware

---

prometheus/promhttp/delegator.go
prometheus/promhttp/delegator_1_8.go
prometheus/promhttp/delegator_pre_1_8.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go

@stuartnelson3 This is crazy…
As it turned out, it's not that esay to guess "common" combination of
interface upgrades. So I decided to just implement all 32 possible
combination of interface upgrades. (Only 16 with Go 1.7 and earlier.)
Clearly, this calls for code generation. But right now, we still need
to find out what's the best form of the code. For later additions,
implementing code generation might be useful.
Note that newDelegator is called for each HTTP request. Thus, this
commit aims to make the upgrade selection quick. (After the type
checks, it's just directly accessing an element in a slice.)

promhttp: Bite the bullet and implement all 32 possible interface combos

---

prometheus/doc.go

Notice `log` line here: https://godoc.org/github.com/prometheus/client_golang/prometheus#hdr-A_Basic_Example

Minor documentation fix

---

prometheus/counter.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/summary.go
prometheus/untyped.go
prometheus/vec.go

@grobie 
This is in preparation for "curried" metric vecs, as discussed.
And it's a good thing anyway. The exported MetricVec was from a time
when I thought people would define own Metric types and then create
Vecs of it. That has never happened.

Unexport MetricVec

---

prometheus/counter.go
prometheus/vec.go

MetricVec is un-experted by now. godoc handles that correctly by
showing the methods of the embedded un-exported metricVec with the
exported type (CounterVec, SummaryVec, ...) that embeds metricVec.
@grobie @ibigbug

Remove remaining references to MetricVec from doc comments

---

prometheus/http.go

The "No metrics encoded" error was erroneously displayed the value of err, not lastErr.
It looks like this could potentially have caused a panic in this error condition, since `err` is never set in scope.

http.go: incorrect error message displayed when no metrics encoded error

---

prometheus/promhttp/http.go

That's the same bug fixed in #342 (which is the deprecated code only
replicated in the `prometheus` package until v0.10 is out).
@brian-brazil @wrouesnel

Fix error reporting bug

---

.travis.yml
README.md

Also, document the version requirement.
Triggered by #333 . @stuartnelson3 @grobie @fabxc any concerns about dropping 1.6 support?
I'd say support for three minor version ought to be enough for anybody. Supporting too many versions will be quite a maintenance overhead, as demonstrated in #333. (We also have separate code for 1.7 and 1.8+ right now, which can be dropped once Go1.10 is out.)

Drop Go1.6 support, add test for Go1.9

---

prometheus/summary.go

Improving docs to warn users about deprecation of `DefObjectives` in Summary type
@beorn7

Change summary docs

---

.gitignore
examples/random/Dockerfile
examples/simple/Dockerfile

When those are published on Dockerhub, people will be able to start those
examples in fewer steps than the current documentation:
https://prometheus.io/docs/introduction/getting_started/#starting-up-some-sample-targets
While relying on Docker may not be always wished, giving the possibility to
quickly start a daemon that exposes metrics can be useful in many tutorials.
This commit tries really hard to limit the number of per-example maintenance
work by sharing most of the Makefile to build the Docker images. The tiny top
level Makefiles in each example directory are strictly identical.
I've also copied the way the main prometheus repo tags its Dockerimage in the Makefile, I assume something else is givin its final tag by overriding DOCKER_IMAGE_NAME and DOCKER_IMAGE_TAG somewhere. …

Create Docker images for the examples

---

prometheus/counter.go
prometheus/desc.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/http_test.go
prometheus/metric.go
prometheus/observer.go
prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go
prometheus/summary.go
prometheus/vec.go
prometheus/vec_test.go

The idea behind it is described in detail in #320 .
This commit also updates the example given in
promhttp/instrument_server_test.go , which nicely illustrates the
benefit of this change.
So far, currying could be emulated by creating different metric vec's
with different values in their ConstLabels. This was quite difficult
to grasp - which is essentially what was done in the example mentioned
above. Now that this use case can be solved without ConstLabels, we
can safely declare ConstLabels as rarely used. (Perhaps we can
deprecate them entirely one day, but I'll take a raincheck on that
when the changes of v0.10 have materialized.) This commit thus also
updates the ConstLabel doc comments in the various Opts. (It contained
fairly outdated stuff anyway.)
@grobie @stuartnelson3 …

 Allow currying of metric vec's

---

prometheus/counter.go
prometheus/counter_test.go
prometheus/gauge.go
prometheus/gauge_test.go
prometheus/go_collector_test.go
prometheus/value.go

@grobie 
@smcquay This is implementing what I had suggested on top of your change.

Make Counter faster for simple Inc or Add with an integer

---

prometheus/benchmark_test.go

This is the simpler of the two tests that I was running, as asked for in #367.
The results of checking out `pre` and `post` the merge of our changes are as follows:
```bash
$ git co pre
$ go test -cpu=64 -benchtime=5s -v -bench Counter$ -run asldjkflaskjdf github.com/prometheus/client_golang/prometheus
goos: darwin
goarch: amd64
pkg: github.com/prometheus/client_golang/prometheus
BenchmarkCounter-64     100000000               65.7 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/prometheus/client_golang/prometheus  6.634s
$ git co post
$ go test -cpu=64 -benchtime=5s -v -bench Counter$ -run asldjkflaskjdf github.com/prometheus/client_golang/prometheus
goos: darwin
goarch: amd64
pkg: github.com/prometheus/client_golang/prometheus
BenchmarkCounter-64     500000000 …
```

Add a benchmark for concurrent counter increments

---

prometheus/promhttp/delegator.go

Previously, the pickDelegator function was not returning a
*hijackerDelegator so the return value did not implement the Hijacker
interface. As a result, code that attempts to hijack the connection
would fail when using a type assertion.
All the other cases returned the hijackerDelegator correctly.

Fix delegator return value for single hijacker

---

prometheus/push/deprecated.go
prometheus/push/example_add_from_gatherer_test.go
prometheus/push/examples_test.go
prometheus/push/push.go
prometheus/push/push_test.go

This allows adding more options in elegant ways, showcased here by
HTTP basic auth and by injecting a custom http.Client.
Fixes #341 and #372.
@grobie @alitari @shlimp

Add completely new push syntax

---

README.md
prometheus/doc.go

For those following that link, make it more obvious
which subpackage they probably want.
@beorn7 @grobie 
Following on for #382. I don't think the new doc text is the best, but it is better.

Add Godoc link at the top of the README

---

prometheus/doc.go
prometheus/promauto/auto.go

Finally, I found an easy solution to provide the "evil"
auto-registration without getting death threats from the wardens of Go
purity. The reasoning can be found in the package's doc comment.
@brian-brazil I think you will like this.
@grobie next time you give an instrumentation introduction, you can use this package and ignore the registry with its Registerer and Gatherer interfaces altogether.

Add a package promauto that provides auto-registering metrics

---

prometheus/promauto/auto.go

This adds the Func variants of NewCounter and NewGauge to the handy promauto package.
@beorn7

promauto: add NewCounterFunc and NewGaugeFunc

---

prometheus/registry_test.go

prometheus/common has changed and now adds the charset to the
Content-Type header.
@grobie

Fix TestHandler

---

prometheus/promhttp/instrument_client_1_8.go

When tracing, it appears `DNSDone` is instead calling the supplied `it.DNSStart` function - _NOT_ `it.DNSDone`. This looks like it would result in no reporting for completed DNS requests.
Per the example code, we would never log "dns_done".
```
trace := &InstrumentTrace{
DNSStart: func(t float64) {
dnsLatencyVec.WithLabelValues("dns_start")
},
DNSDone: func(t float64) {
dnsLatencyVec.WithLabelValues("dns_done")
},
TLSHandshakeStart: func(t float64) {
tlsLatencyVec.WithLabelValues("tls_handshake_start")
},
TLSHandshakeDone: func(t float64) {
tlsLatencyVec.WithLabelValues("tls_handshake_done")
},
}
```
Please forgive if I am missing anything obvious here... :)

promhttp: fix DNSDone should call Done, not Start

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Fixes #337. Adds support for `DeleteSeries`, `CleanTombstones`, and `Snapshot` as documented [here](https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-admin-apis).
@beorn7

Add support for API admin methods

---

.travis.yml

* Add Go 1.10.x.
* Fix indenting.
* Run all tests.
Signed-off-by: Ben Kochie <superq@gmail.com>

Update travis Go versions

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

400 and 422 are documented error codes from Prometheus, so we should attempt to parse the error returned for both of them.  Discussed briefly on IRC last night.
Needed to change a test that was requiring the old behaviour - made it use 500 instead of 400.
@beorn7 as maintainer

Decode JSON body when Prometheus returns 400 to an api call

---

prometheus/examples_test.go
prometheus/registry.go

Also, clarify in the doc comment.
Previously, the assumption was that inconsistent label dimensions are
violating the exposition format spec. However, especially with the
knowledge that OpenMetrics will explicitly allow inconsistent label
dimensions in expositions, we should allow it in client_golang, too.
Note that registration with proper Descs provided will still check for
consistont label dimensions. However, you can "cheat" with custom
Collectors as you can collect metrics that don't follew the provided
Desc (this will be made more explicit and less cheaty once #47 is
fixed). You can also create expositions with inconsistent label
dimensions by merging Gatherers with the Gatherers slice type. (The
latter is used in the Pushgateway.)
Effectively, normal direct instrumentation will …

Relax consistency checks during gathering

---

api/client.go

As per https://golang.org/pkg/net/http/#Transport.Dial documentation says
```
// Deprecated: Use DialContext instead, which allows the transport
// to cancel dials as soon as they are no longer needed.
// If both are set, DialContext takes priority.
```

Update DefaultRoundTripper to DialContext because Dial is deprecated

---

prometheus/collector.go
prometheus/doc.go
prometheus/registry.go
prometheus/registry_test.go

Fixes #47 . See there for more detailed discussion.
@grobie this removes the need to return "dummy" descriptors as it has been done by countless exporters so far.

Introduce unchecked Collectors

---

prometheus/promhttp/delegator.go
prometheus/promhttp/delegator_1_8.go

Without doing so, they don't actually implement the interfaces they claim to.
EDIT: They do implement the interfaces in actual usage but can now more universally do so regardless of how they are references (value or pointer)

Make delegators wrapping responseWriterDelegator have value receivers

---

prometheus/examples_test.go
prometheus/registry.go
prometheus/registry_test.go
prometheus/summary.go
prometheus/summary_test.go

Add more checks around summaries and histograms

---

prometheus/examples_test.go
prometheus/metric.go

Supersedes #407 .
@simonpasquier 

Add a wrapper to add a timestamp to a metric

---

.travis.yml
Makefile
Makefile.common

This pull request aims to close #430. 
@beorn7, other prometheus projects use the following make command, should I set it here too? 
make check_license style unused test staticcheck
Signed-off-by: glefloch <glfloch@gmail.com>

Add prometheus common makefile

---

Dockerfile

Using the recommended label syntax for maintainer in Dockerfile.

---

.travis.yml
Makefile

This is reinstating the old behavior. The longer tests are not only
long but also flaky. (The former is by design, the latter is a bug.)
@simonpasquier @glefloch

Add test-short target and use it in CI

---

prometheus/internal/metric.go
prometheus/registry.go
prometheus/testutil/testutil.go

This is for types we don't want to export but which are used in
different packages within client_golang.
Currently, that's only NormalizeMetricFamilies (used in the prometheus
package and in the testutil package). More to be added as needed.
@grobie

Create an internal package

---

prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go
testutils/testutils.go
testutils/testutils_test.go

This is derived from #423. I recreated it so that it is pulling from a branch I can push to...
Changes to #423 are based on the review that has already happened. I packaged it nicely in commits with messages, so you can follow along.
I will add more documentation and the single-value retrieval helpers (cf. #230) in a separate PR. Same with the creation of an internal package for the duplicated code. Don't want to put too many things into this one PR.
@grobie @brancz

Add testutil package

---

prometheus/desc.go
prometheus/examples_test.go
prometheus/metric.go
prometheus/registry.go
prometheus/value.go

The only known external usage of it was in prometheus/pushgateway,
where it was removed by
https://github.com/prometheus/pushgateway/pull/200 .
Originally, the expectation was that users would implement the Metric
interface now and then. As we know now, neither it is happening, nor
would it make a lot of sense. (Users implement the Collector interface
instead.) By now, LabelPairSorter is essentially noise in the already
quite cluttered namespace in the prometheus package.

Un-export prometheus.LabelPairSorter

---

prometheus/histogram.go
prometheus/histogram_test.go

@stuartnelson3 you might enjoy reviewing this. (Also, @grobie is on vacations...)
Fixes #275
This is rather tricky and required some studying of the Go memory
model. I have added copious code comments to explain what's going on.
Benchmarks haven't changed significantly, despite the additional
atomic operations now required during Observe. Write performance is
noticable, but it is also much more involved now and has a mutex. (But
note that Write is supposed to be a relatively rare operation and thus
not in the hot path compared to Observe.) Allocs haven't changed at
all.
OLD:
```
BenchmarkHistogramWithLabelValues-4     10000000               151 ns/op               0 B/op          0 allocs/op
BenchmarkHistogramNoLabels-4            50000000                36.0 ns/op             0 B/op …
```

Lock-free atomic observations in Histograms!

---

prometheus/histogram_test.go

it appears there is a copy/paste error in the exponential buckets test failure message which is fixed here.  @beorn7 does this seem right?

fix exponential buckets failure message

---

prometheus/registry.go
prometheus/registry_test.go

Fixes #471 .
@douglas-reid this is not yet the fix for https://github.com/istio/istio/issues/8906 but it will create the right error message. And it will detect formerly undetected occurrences of the problem.

 Add check for duplicated label name

---

api/prometheus/v1/api.go

This pull request fixes a problem where 204 responses are parsed as JSON. This incorrectly results in an error of `bad_response...`, since HTTP 204 is "No Content" and represents a successful response.
Signed-off-by: Adam Jaso <2285656+adamjaso@users.noreply.github.com>

Do not parse json on 204 responses

---

prometheus/registry_test.go

@douglas-reid @bobbytables this should test what you are doing in istio. Failure to fail here tells me the bug is either already fixed (and should be fixed in istio once using the current version of client_golang) or something else is happening in the Istio code.

 Add a concurrent end-to-end test for observe-register-gather

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Fixes: #479 
Signed-off-by: Marcin Owsiany <marcin@owsiany.pl>
cc @krasi-georgiev

Add a way to return the body of a 5xx response.

---

prometheus/registry.go
prometheus/registry_test.go

@beorn7
This is my attempt to add (similar, and implementation copied from, [client_python](https://github.com/prometheus/client_python/blob/master/prometheus_client/exposition.py#L186)) WriteToTextfile for a Registry.
This is so we can write Go tools that emit Node Exporter textfiles.
My strategy is to create the same output from the promhttp HTML website.

WriteToTextfile function for node exporter textfiles

---

prometheus/counter.go
prometheus/examples_test.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/labels.go
prometheus/summary.go

Add more info to the inconsistent cardinality errors

---

prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go

Fixes #494.
@PhilipGough thanks for reporting, please have a look.
@brancz I think the "upstream" code for the testutil package is gone from KSM by now. So no action required there, I guess.

Fix testutil metric comparison

---

prometheus/example_clustermanager_test.go

Or if that's too verbose, can we just add the `http.Handle("/metrics/inner", promhttp.HandlerFor(reg, promhttp.HandlerOpts{}))`  line to help the new user?

Add the last few lines needed to show a new user how the Collector/Gatherer fits together

---

prometheus/registry.go
prometheus/registry_test.go

This fixes #512 and subsequently https://github.com/istio/istio/issues/10236 .
@douglas-reid , this incorporates your findings. Please have a look.

Fix the race in the registry

---

go.mod
go.sum
prometheus/promhttp/http_test.go
prometheus/registry_test.go
prometheus/testutil/testutil_test.go

This updates the Go modules and it will then also fix the pre-Go1.11 builds (which always build from head of the dependencies).

Adjust to breaking change in prometheus/common

---

prometheus/doc.go

Fix some spelling errors in [doc.go](https://github.com/prometheus/client_golang/compare/master...JoeWrightss:patch-1?expand=1#diff-f67a8a57acf0512d150dc32ce5011c5a):
1. "marke" to "make".
2. "porformed" to "performed".

Fix some spelling errors

---

Makefile.common
prometheus/push/push_test.go
prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go

This should fix the staticcheck test failures with Go 1.10

Update Makefile.common to current upstream version

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

This PR adds support for fetching [rules](https://prometheus.io/docs/prometheus/latest/querying/api/#rules) via the `/api/v1/rules` endpoint using the API client. Currently, the API client exposes no way to do this and it would be nice to have for external systems that wish to retrieve this information.
cc @beorn7

Add support for fetching rules with API client

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

The `/targets` endpoint generates a JSON decoding error when you try to send a request to it while having the Node Exporter configured in Prometheus. It looks like discovered labels are being presented as is, without any validation. In particular I received this error: `"__param_collect[]" is not a valid label name`.
Here is the part of Prometheus server code that uses a `map[string]string` to describe discovered labels internally.
https://github.com/prometheus/prometheus/blob/a1f34bec2e6584a2fee9aec901f3157e3e12cbaa/web/api/v1/api.go#L505-L517

Use a map to describe discovered labels, as they are not validated by the server

---

api/client.go

This PR fixes what seems to be a data race condition. Previously if the caller of this Do() canceled the context, or the provided context has timed out the select statement would enter that branch and then close the response body. This could potentially occur concurrently with launched go routine on line 115. My solution simply moves the receive on the done channel before the close of the resp body. 
May want to consider whether we check context in the go routine launched on line 115 before reading the body as a good measure of "don't do work you don't need too". I'll wait for initial comments on this PR to make sure my logic is correct. 
fixes https://github.com/prometheus/client_golang/issues/531

wait for done before writing to shared resp body

---

Makefile.common

This should fix the currently broken Travis builds for Go versions
before 1.11.

Pull in new Makefile.common from prometheus/prometheus

---

prometheus/histogram.go

* one allocation for duo instantiations
* use index overflow instead of redundant last state field
name                         old time/op    new time/op    delta
HistogramWithLabelValues-12     204ns ± 0%     204ns ± 0%   ~     (all equal)
HistogramNoLabels-12           41.1ns ± 0%    40.5ns ± 0%   ~     (p=1.000 n=1+1)
HistogramObserve1-12           33.1ns ± 0%    33.9ns ± 0%   ~     (p=1.000 n=1+1)
HistogramObserve2-12            132ns ± 0%     122ns ± 0%   ~     (p=1.000 n=1+1)
HistogramObserve4-12            377ns ± 0%     364ns ± 0%   ~     (p=1.000 n=1+1)
HistogramObserve8-12           1.00µs ± 0%    0.96µs ± 0%   ~     (p=1.000 n=1+1)
HistogramWrite1-12             1.80µs ± 0%    1.76µs ± 0%   ~     (p=1.000 n=1+1)
HistogramWrite2-12             3.28µs ± 0%    3.25µs ± 0%   ~ …

Save memory on histograms: slightly faster with less code

---

prometheus/push/push.go

Allow users to specify which format the pusher should push in.
Also added tests related to changing the format of the pusher.
This does not break existing functionality since the argument
is varadic.
@beorn7 
Signed-off-by: Frank Spitulski <fspituls@ucsd.edu>

feat(push): add format builder option

---

prometheus/promhttp/instrument_client_1_8_test.go

This is similar to
https://github.com/prometheus/client_golang/pull/535 fixing ExampleInstrumentRoundTripperDuration.
cc @brancz @mxinden @beorn7

prometheus/promhttp: actually observe values in trace in example

---

go.mod
go.sum
prometheus/graphite/bridge.go
prometheus/graphite/bridge_test.go

The context package is available since Go 1.7 which is the minimal version supported by client_golang.
Found this after reading https://medium.com/@valyala/stripping-dependency-bloat-in-victoriametrics-docker-image-983fb5912b0d (mentioned by @brian-brazil on IRC). Though the complain isn't really convincing to me as dependency managers should be smart enough to vendor only the required packages and the library rely mostly on stdlib packages.

*: replace golang.org/x/net/context by context

---

api/prometheus/v1/api.go

cc @krasi-georgiev this was missed, so right now it sends it as query params and post body for the post request.

Remove encode of params in query before DoGetFallback

---

prometheus/wrap_test.go

Hi. Find a typo and hope to fix it for the perfection of the code.
client_golang/prometheus/wrap_test.go：
Line 289: "succeded" is a misspelling of "succeeded"   
Line 298: "succeded" is a misspelling of "succeeded"

fix: fix a typo

---

prometheus/counter_test.go

The previous `float64(math.MaxUint64 + 1)` is too close to
`float64(math.MaxUint64)` to actually overflow as indended.
The counter code is actually converting forward and backward and
compare the original and twice-converted value. On most platform, this
will create a deviation and thus trigger the expected behavior. By
sheer "luck", one might end up with the same value and thus still use
the uint64 representation. Which is OK within the precision we can
expect. But it breaks the test. With this change, the next
representable floating point value greater than the floating point
value used to represent math.MaxUint64 is used.
@xnox this should fix #530. Could you verify?
@TheTincho you might have seen this issue, too, for the Debian builds on the affected platforms.

Make TestCounterAddLarge more robust

---

prometheus/go_collector.go
prometheus/go_collector_test.go

If memstats couldn't be collected within 1s, they will simply be
skipped.
Also, document the issue comprehensively.
Sooooo, this is the simplest possible way to address #551. Or let's say it is the second simplest way.
The simplest way would be to not do anything about it (besides describing the problem in the doc comment) and wait/hope for Go1.13 to finally fix https://github.com/golang/go/issues/19812 . Until that has happened, users affected by #551 will have occasional scrape timeouts. That's at least clean, but since the Go collector is there by default, most of the affected users will probably not have read the warning in the doc comment and will be as puzzled by the timeouts as @bboreham was.
The idea in this PR is to simply skip the memstats metrics in the (rare) cases where it …

Return previous memstats if Go collector needs longer than 1s

---

prometheus/promhttp/delegator.go

On commit 1173d734050af725504a9b2fbe93bff0b16f1b53 the push function was removed. Causing issue with wrappers that implement that function. If the wrapper implemented that function the delegator would fall in the range [16-31] and with NewDelegator returning a nil value. This then caused a panic.
This patch pulls back part of the removed items on 173d734050af725504a9b2fbe93bff0b16f1b53.

Fix regression issue 574

---

prometheus/examples_test.go

We stopped advertising binary-wide setting of a label quite a while
ago. This doc comment was missed in the cleanup.
@brian-brazil @Ashish-Bansal follow-up to the discussion in https://github.com/prometheus/client_python/issues/406

Remove outdated use-case description from doc comment

---

api/client.go
api/prometheus/v1/api.go
api/prometheus/v1/api_test.go
go.sum

closes https://github.com/prometheus/client_golang/issues/560
This adds `storage.Warnings` to the error return of Query and QueryRange. Unfortunately the client.Do() method interface makes this a bit difficult to implement. 
So either we go down this path (where the specific error is a known type people should check for) *or* we need to change the Do() methods' interface to return a separate "warning" error.

Add storage.Warnings to client

---

prometheus/go_collector_test.go

It is perfectly possible that a normal GC happens just before the
forced one. Thus seeing 2 GCs is fine.
Whenever this test failed, it was because two GCs were seen.
Signed-off-by: beorn7 <bjoern@rabenste.in>

Unflake TestGoCollectorGC

---

prometheus/go_collector_test.go

This is really lame as it essentially just uses longer times to
wait. The test is still timing-dependent and thus could still
theoretically fail with unlucky scheduling. However, we are testing
something that _is_ about timing. Turning this all into something not
timing-dependent would be first quite involved and second might defeat
the purpose of testing code that is inherently about timing.
Let's see how this works out in practice.
Signed-off-by: beorn7 <bjoern@rabenste.in>

Attempt to fix flakiness of TestGoCollectorMemStats

---

go.mod
go.sum
prometheus/process_collector.go

 Remove use of deprecated procfs functions

---

prometheus/promhttp/http.go
prometheus/promhttp/http_test.go

The doc comments explain the rationale in a quite detailed way.
Fixes #543 and #542
I'll add a test once we have decided this is the way to go.

Add an error counter for internal errors in the HTTP handler

---

examples/random/main.go
prometheus/build_info.go
prometheus/build_info_pre_1.12.go
prometheus/go_collector.go

This is now kind of meant as complementary to https://github.com/povilasv/prommod , see doc comment. https://github.com/povilasv/prommod is concerned with the dependencies, while this simple collector is only doing the main module. It is, if you want, the poor person's version of prometheus/common/version. If you build your binaries in the "right" (modules) way, you get the version info for free without setting any build variables.
Since many users might not build their binaries in that "right" way yet, and some might not want to disclose their package path or version, this collector is not registered with the default registry.

Add a simple buildInfoCollector

---

api/client.go
api/client_test.go
api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Without this we have 2 problems:
(1) we cannot differentiate an error from a warning from the API response body (as the `Err()` method is returning self always
(2) we can inadvertently layer these errors together when using `NewErrorAPI`
This PR addresses both.

Pass warnings through on non-error responses

---

go.mod
go.sum
prometheus/process_collector.go
prometheus/process_collector_other.go
prometheus/process_collector_windows.go
prometheus/process_collector_windows_test.go

This PR implements a process collector for Windows, resolves #376.
Some discussion points:
- The `process_cpu_seconds_total` uses an underlying data source that is, from my understanding, incremented with a resolution of ~16 ms. There might be better APIs to use? The ones I've found work with cycles, though, which isn't that easy to convert to seconds.
- There aren't really "file descriptors" on Windows. I did an interpretation of it to be handles (which covers lots of different things in addition to files) instead. And there is a hard-coded max of 16M handles per process.
- I'm not fully sure I did the mapping for Linux memory concepts to Windows correctly. Would love a sanity check there.

Implement process collector for Windows

---

prometheus/process_collector.go

- Now also works on MS Windows. Thanks @carlpett.
- The hints for updating from older versions is obsolete by now.
@carlpett we totally forgot to update the doc comment.

Update doc comment of NewProcessCollector

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

API ref https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names

Add /labels API to client

---

prometheus/registry.go
prometheus/registry_test.go
prometheus/wrap.go

@lukedirtwalker please have a look. This should fix your use case.

Make the AlreadyRegisteredError useful for wrapped registries

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Add warnings to series

---

prometheus/push/push.go
prometheus/push/push_test.go

Fixes #611.
@nnoto what do you think?
This allows
```Go
push.New("http://localhost:9091", "some_job").Grouping("foo", "bar").Delete(),
```

Add Delete method to Pusher

---

api/prometheus/v1/api.go

Prometheus has issues parsing RFC3339Nano timestamps if the year has more than 4 digits, in addition it is the second-pass parse attempt. Since this is a client library and the interface is a `time.Time` it makes sense that we pick the clearest simplest format-- so I propose we use the `model.Time` representation of time in our communications to prometheus. This (1) removes the issues with timezones in those queries going downstream and (2) completely works around this #614 issue as the parsing mechanism in prometheus can handle those times in this format.
Related to #614

Change all time formatting to UTC and off of time.RFC3339Nano

---

api/prometheus/v1/api.go

Fixup for #617
Fixes https://github.com/prometheus/client_golang/issues/614
cc @beorn7

Handle formatting when the time in nanoseconds requires more than a single int64

---

prometheus/push/push.go
prometheus/push/push_test.go

This should only be released after PGW 0.9 is released.
Interestingly, the code had a bug so far as it would neither properly URL-encode label values with special characters nor reject them (as long as none of the special characters was a `/`). Nobody noticed so far…

Support new base64 encoding for pushing to the Pushgateway

---

api/prometheus/v1/example_test.go

Closes #194
cc: @krasi-georgiev

Provide godoc examples for using the api

---

prometheus/promhttp/delegator.go

Flush is another of the methods that will call WriteHeader if it
hasn't happened yet. Since we want to call observeWriteHeader (if
set), we need to do the WriteHeader call already here, similar to what
we have done in Write and ReadFrom.
This commit also adds comments explaining the above to not tempt
developers to remove the WriteHeader call.
Signed-off-by: beorn7 <beorn@grafana.com>

Add WriteHeader call to Flush

---

prometheus/push/push.go
prometheus/push/push_test.go

- Match fake-Pushgateway's behavior to v0.10+ in the test.
- Use constants for status code, not number literals.

Minor improvements to the push code

---

prometheus/metric.go

The `const separatorByte` wasn't used anymore actually. In `vec.go`,
we were using `model.SeparatorByte`, which is better anyway. So remove
the unused constant and initialize `separatorByteSlice` with
`model.SeparatorByte`, too.
@cstyan follow-up to your comment on #657 .

Use a cleaner initialization of `separatorByteSlice`

---

prometheus/registry.go
prometheus/registry_test.go

This PR fixes the regression from 1.2.0 where the calculation of `collectorID` changed during `Register()`, but not during `Unregister()`
~It also brings the vec code closer to the rest by addopting `xxhash` everywhere.~ (reverted, see https://github.com/prometheus/client_golang/pull/663#issuecomment-543145728)
Finally, we also add a simple test case to ensure this doesn't happen again! :wink:  
fixes #662

Fix collectorID calculation for Unregister()

---

prometheus/vec.go

Contrary to the code comment, I see no `basicMetricVec` implementation. Grep'ing this project shows this is the only reference. So I suspect it's an outdated comment and can be removed to minimize confusion.
I'm unclear whether other parts of that comment are also incorrect and need updating.

Remove old reference to basicMetricVec

---

prometheus/graphite/bridge.go
prometheus/graphite/bridge_test.go

Hello! I have added some changes to the Bridge struct 
and related methods to make it possible to use Graphite tags

Send Graphite metrics with tags

---

api/prometheus/v1/example_test.go

Hi :wave:.  I'm coming from reading this example at https://godoc.org/github.com/prometheus/client_golang/api/prometheus/v1#example-API--Query.  (thanks #630)
In that rendered doc, one only sees the example body, package imports and their aliases are invisible.
It'd be reasonable to guess that `api` refers to `github.com/prometheus/client_golang/api`, it's the only directory of that name here.
However, below it becomes shadowed by a variable of same name `api := v1.NewAPI(client)`, which makes the whole example very confusing to read!  (I didn't even know you can do that in Go – access an import in same function before a variable of same name...)
This is an attempt to rename the variable, leaving package names at their default so one can still guess what they refer to.
cc @krasi-georgiev

api client examples: avoid shadowing package with variable

---

prometheus/gauge.go

- Simplify confusing wording about concurrency safety.
- Add link to example for info metric.
@finkr does this help?
Fixes #693 .

Improve doc comment for NewGaugeFunc

---

api/client.go
api/client_test.go
api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

This PR replaces #648.
- Moved warnings from the `api` package to `api/prometheus/v1`
- Split the `api.Client` interface.  Previously it was being used in both `api` and `v1`.  Now a separate interface (`v1.apiClient`) better defines this internal http client.
- Moved DoGetFallback into method into `v1`
- Moved tests as appropriate.
- Correctly returned warnings from `Do` and `DoGetFallback`.

Return Prometheus Warnings

---

prometheus/go_collector.go

Fixes #618.
@bboreham please have a look.

Improve doc string for `go_gc_duration_seconds`

---

prometheus/testutil/testutil.go

:wave: 
I would like to propose additional function to `testutil.go` which will count metrics in a given Collector. The example usage can be seen here: https://github.com/thanos-io/thanos/blob/d758432436718ff6cd0d9136bc53653f4ec5cf47/pkg/compact/compact_e2e_test.go#L179
I also read the package documentation and I think I can agree that mock would be preferred for all of those test assertions IF such mock would be ready to use somewhere AND it would be easy to inject those mocked counter, gauges etc. The latter might be even impossible given the `*Vec` metrics are not interfaces e.g:
```
func NewCounterVec(opts CounterOpts, labelNames []string) *CounterVec {
```
Overall I think, with this small function `testutil` gives all you need to unit test your instrumentation without mocks, except …

Added `testutil.CollectAndCount`

---

examples/random/main.go
prometheus/counter.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/observer.go

This is, sadly, the only way to avoid a breaking change. The cost is
that anyone using exemplars has to perform a type assertion. This is,
however, a common pattern where interfaces turn out to need additional
methods in a stable library or only some implementations can provide
the additional methods (AKA "interface upgrade").
Needless to say that in v2 of this library, we'll do things in a more
straight forward way.
By now, I'm fairly confident we need to go down this way. It would be extremely confusing and damaging if enough users got bitten by the original approach so that we had to revert to the approach in this PR anyway.
The trade-off in this PR is the following: I'd expect relatively few users to use exemplars. And those who do are most likely advanced users who are not shocked by …

Pull out ...WithExemplar methods into separate interfaces

---

prometheus/counter.go

The now fn is not initialized for counters on the `CounterVec` initialization path. Adding that here.

Initialize now fn for counter

---

prometheus/vec.go

Interestingly, methods implicitly forwarded from embedded types are
detected by GoDoc if they are just one level deep. Methods of embedded types in
the embedded type are not recognized. This commit therefore adds
explicit forwarding methods for Collect, Describe, and Reset.
@bwplotka I discovered that while working on the promauto changes. Please have a look, easy review. (o:

Explicitly forward metricVec methods Collect, Describe, Reset

---

prometheus/doc.go
prometheus/promauto/auto.go
prometheus/value.go

Besides the scary naming (happy to hear better ideas than the dreaded "factory"), the whole package documentation needs to updated, should we go down this path. (We don't need to talk about how promauto only works with the global registry anymore.)
@bwplotka I think this comes close to your request for a `promauto` extension, but it is done in a way that reads more nicely than an additional `Registerer` parameter in each constructor function.

Add a "factory" to make promauto work for custom registries

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Introduces support for the new metadata endpoint from Prometheus. The new endpoint provides information independent of targets and collapses the unique combinations of HELP, TYPE and UNIT.
Fixes #705
Signed-off-by: gotjosh <josue@grafana.com>

API Client: Support new metadata endpoint in v1

---

.circleci/config.yml

I'm opening it now so I don't forget about it but I'll be off most of next week so no rush merging it. I've tested it by enabling Circle CI in my fork and it passes.
Once/when this is merged, I suggest that we run both Travis and Circle CI in parallel before turning off Travis.

Add Circle CI configuration

---

prometheus/promhttp/delegator.go
prometheus/promhttp/http.go

Essentially, just don't try to set a status code and send any error
message in the body once metrics gathering has succeeded. At that
point, the most likely reason for errors is anyway that the client has
disconnected, in which sending an error is moot. The other possible
reason for an error is a problem during metrics encoding. This is
unlikely to happen (it's a coding error here in client_golang in any
case), and if it is happening, the odds are we have already sent
something to the ResponseWriter, which means we cannot set a status
code anymore. The doc comment for HTTPErrorOnError now describes these
circumstances explicitly and recommends to set a logger to report that
kind of error.
This should fix the reason for the infamous `superfluous
response.WriteHeader call` message.
@lidel …

Fix promhttp error handling

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Signed-off-by: huanggze <loganhuang@yunify.com>
The current way we handle error drops some info from `errorType` and `error` for some scenarios. 
Consider a real response example below, we expect the error object carry more info than `inconsistent body for response code`. 
```json
HTTP OK
---
{
"status":"error",
"errorType":"internal",
"error":"multiple matches for labels: many-to-one matching must be explicit (group_left/group_right)"
}
```

Improve API error handling

---

prometheus/process_collector_windows.go

Ref: https://github.com/prometheus/client_golang/issues/728

fix: process_resident_memory_bytes detected is incorrect in Win7 32bit

---

prometheus/promhttp/instrument_client_test.go

Signed-off-by: RainbowMango <renhongcai@huawei.com>
The following tests will fail when run with Go 1.14+:
```
[root@ecs-d8b6 client_golang]# go test ./prometheus/promhttp/ -run=TestClientMiddlewareAPIWithRequestContextTimeout
--- FAIL: TestClientMiddlewareAPIWithRequestContextTimeout (0.10s)
instrument_client_test.go:190: want error "Get http://127.0.0.1:45001: context deadline exceeded", got "Get \"http://127.0.0.1:45001\": context deadline exceeded"
FAIL
FAIL	github.com/prometheus/client_golang/prometheus/promhttp	0.106s
```
The difference is whether the string included by double quotation marks.
Got: `"http://127.0.0.1:45001"`
Expected: `http://127.0.0.1:45001` (no `""`)
The error msg printed by Go `net/url` package, but the formatting has been changed in Go1.14.
Go 1.14-, such as …

Fix unit test failing with Go1.14+

---

prometheus/counter.go
prometheus/examples_test.go

Document the example usage of ConstLabels to register several GaugeFuncs on the same metric name.
Ref: https://github.com/prometheus/client_golang/pull/736

GaugeFunc: ConstLabels godoc example

---

prometheus/testutil/promlint/promlint.go
prometheus/testutil/promlint/promlint_test.go

Refer https://github.com/prometheus/prometheus/issues/5317.
I split this work into two commits:
- Porting : Just simply copy `promlint` in.
- Minor Improvement: Fix static check warning by some IDE, such as Goland. [More Deatils](https://github.com/prometheus/prometheus/pull/6445#issuecomment-564468169)
I wish it will be easier for the reviewer to catch what has been changed during porting.

Porting promlint from prometheus/prometheus

---

prometheus/testutil/lint.go
prometheus/testutil/lint_test.go
prometheus/testutil/promlint/promlint.go
prometheus/testutil/testutil.go

This for one adds direct `MetricFamily` support to `promlint`.
It then adds helpers `CollectAndLint` and `GatherAndLint` akin to `CollectAndCompare` and `GatherAndCompare` to the `testutil` package, which simplifies to integrate linting into testing of instrumented code.
@RainbowMango

Add linter helpers to testutil

---

prometheus/push/push.go
prometheus/push/push_test.go

An empty job name was always an error, but it was previously only
detected when pushing to the PGW and receiving an error. With this
commit, the error is detected before pushing.
An empty label value should have been OK but was encoded in a way that
couldn't be pushed to the
PGW. Cf. https://github.com/prometheus/pushgateway/issues/344 . This
commit changes the creation of the path in the URL so that it works
with empty label values.
@matevz
Fixes #750 .

Properly handle empty job and label values

---

prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go

Now that we have also added CollectAndLint and GatherAndLint, I
thought we should bring CollectAndCount in line. So:
- Add GatherAndCount.
- Add filtering by metric name.
- Add tests.
Minor wart: CollectAndCount should now return `(int, error)`, but that
would be a breaking change as the current version just returns
`int`. I decided to let the new version panic when it should return an
error. An error is anyway very unlikely, so the biggest annoyance here
is really just the inconsistency.
@bwplotka you might like this.
@cstyan you needed this recently (but as already discussed, with `promauto` you won't, but your request still inspired this PR)

Improve CollectAndCount

---

Makefile
prometheus/counter_test.go
prometheus/desc.go
prometheus/examples_test.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/metric.go
prometheus/registry.go
prometheus/registry_test.go
prometheus/summary.go
prometheus/value.go
prometheus/wrap.go
prometheus/wrap_test.go

`github.com/golang/protobuf/proto` is deprecated in lieu of
`google.golang.org/protobuf/proto`. However, we cannot simply
migrate. Types from the proto package are exposed to users of packages
in this repo. If we migrate here, users have to migrate to. Thus, we
could only migrate with a major version bump.
In different news, with all the inline lint:ignore comments, including
the existing ones, there is no need to repeat the exception in the
Makefile.
A current version of `staticcheck` is happy with the code after this
commit. golangci-lint is broken at the moment, however, and ignores
the lint:ignore comments in the code as well as those via envvar.
@bentucker this does not fix the golangci-lint problem, but at least it addresses the legitimate protobuf deprecation warnings that even the …

Add lint:ignore for protobuf deprecation

---

go.mod
go.sum

github.com/golang/protobuf@v1.4.0 deprecated something and it leads to a little bit risk if it uses with `github.com/gogo/protobuf`. And some deprecated function has been added back in `github.com/golang/protobuf@v1.4.2`.
Fore details discussion, please refer to :
- https://github.com/golang/protobuf/issues/1126
- https://github.com/kubernetes/kubernetes/pull/90582#discussion_r424861575

Bump github.com/golang/protobuf to v1.4.2

---

prometheus/testutil/promlint/promlint.go
prometheus/testutil/promlint/promlint_test.go

Signed-off-by: Matt Layher <mdlayher@gmail.com>
I'm exporting metrics from my new Elgato Key Light and the device exposes the color temperature of its light in Kelvin, e.g. 4200K. I don't think this measurement would make any sense in Celsius and propose allowing Kelvin as a "base unit", but still recommending that "kelvins" be changed to "kelvin".

testutil/promlint: allow Kelvin as a base unit for color temperature

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Adds support for the status/runtimeinfo API endpoint as per the API docs https://prometheus.io/docs/prometheus/latest/querying/api/#runtime-information
Closes #746
cc @beorn7

api/prometheus/v1/api.go: Add support for status/runtimeinfo endpoint

---

prometheus/promauto/auto.go

In particular, point out that `With(nil)` is valid.
Signed-off-by: beorn7 <beorn@grafana.com>

Improve doc comments in promauto

---

prometheus/promauto/auto_test.go
prometheus/wrap.go
prometheus/wrap_test.go

Passing a `nil` is useful in tests, but our treatment of `nil` is inconsistent.  
This code does not panic:
```go
promauto.With(nil).NewCounter(...)
```
Where as the following does panic.
```go
promauto.With(prometheus.WrapRegistererWith(prometheus.Labels{"foo": "bar"}, nil)).NewCounter(...)
```
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

Ensure that nil registers are treat as a no-op, even when wrapping.

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

add start/end parameter for LabelNames

---

prometheus/histogram.go

This method calls NewConstHistogram.

histogram.go: fix copy/paste typo

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Two primary updates:
- api/prometheus/v1/api.go: Add support for tsdb endpoint
- api/prometheus/v1/api_test.go: Add test case for tsdb endpoint
Signed-off-by: Hima Varsha <hdureddy@apple.com>

Add support for tsdb endpoint

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Use time.Time for timestamps in Runtimeinfo

---

prometheus/vec.go

If we remove metric from slice, last value in old `metrics` still has value of `metricWithLabelValues` and holds reference to `Metric` (see Note in https://github.com/golang/go/wiki/SliceTricks#delete-without-preserving-order).
```
m.metrics[h] = append(metrics[:i], metrics[i+1:]...)
```
So we must zero last value in old metrics slice after we ressliced `metrics`.
```
old := metrics
m.metrics[h] = append(metrics[:i], metrics[i+1:]...)
old[len(old)-1] = metricWithLabelValues{}
```
Signed-off-by: Dima Kozlov <hummerd@mail.ru>

Remove reference to Metric after reslicing

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

The Standard Library later added a 422 status code. 
https://github.com/golang/go/commit/b9ec0024fbc18dd94eff7240afd82fac6b4d8fdc

Replace with the standard library constant.

---

prometheus/metric.go
prometheus/summary.go
prometheus/wrap.go

I assume older Nanoc versions rendered the anchors with commas, but
the current doesn't.
Also, this adds the same link to another doc comment where it is also
relevant.
Signed-off-by: beorn7 <beorn@grafana.com>

Remove spurious commas from links to the docs site

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

When discussing #801, I remembered #794. While dealing with the
latter, I read the HTTP RFC, stumbling upon the following:
When a request method is received
that is unrecognized or not implemented by an origin server, the
origin server SHOULD respond with the 501 (Not Implemented) status
code.  When a request method is received that is known by an origin
server but not allowed for the target resource, the origin server
SHOULD respond with the 405 (Method Not Allowed) status code.
Concluding from that, it is possible that a server desiring a fallback
to GET will send a status code of 501. It is even preferred if that
server does not offer any resource to be used with the POST method.
Therefore, I think we should fallback to GET on a 501, too.
@joe-elliott it would be great if you could …

API client: Enable fallback on status code 501, too

---

prometheus/counter.go
prometheus/desc.go
prometheus/example_metricvec_test.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/summary.go
prometheus/value.go
prometheus/vec.go

MetricVec was already exported in early versions of this library, but
nobody really used it to implement vectors of custom Metric
implementations. Now #796 has shown up with a fairly special yet valid use case
for which I'd prefer a custom implementation of a special
"auto-sampling histogram" outside of this library. Therefore, I'd like
to reinstate support for creating vectors of custom Metric
implementations.
@MikeSpreitzer @lavalamp is that helpful? If yes, I'd be grateful for a review of this PR.
I played around for quite some while with the option of a separate
package providing the tools one would need to create vectors of custom
Metric implementations. However, with the current structure of the
prometheus/client_golang/prometheus package, this leads to a lot of
complications with …

Export MetricVec (again)

---

prometheus/process_collector.go
prometheus/process_collector_test.go

for the enhancement: https://github.com/prometheus/client_golang/issues/760

add the NewPidFileFn to helper

---

prometheus/promhttp/http.go
prometheus/registry.go

Note that changing the behavior will only be possible in v2 and is tracked in #820 .

Be more explicit about the multi-line properties of MultiError

---

prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go

Without this fix, the `InstrumentHandler...` middlewares get locked in
an endless loop in case of an invalid Collector, eating all the memory.
@AlekSi

promhttp: Correctly detect invalid metric and label names

---

prometheus/metric.go
prometheus/vec.go

- Fix typo in comments
@beorn7

Fix typo in comments

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
As pr https://github.com/prometheus/prometheus/pull/8301 was merged, this pr adds `matches` to `LabelNames` and `LabelValues` APIs. 
One thing I am not very sure is the testing, seems we are just mocking the HTTP response in the unit tests, it cannot really ensure correctness. But I already test this manually and it works.

Support matchers in labels API

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
This pr adds exemplars API support.
I added one unit test and also tested it locally.

Add exemplars API support

---

prometheus/summary.go

Fixes: https://github.com/prometheus/client_golang/issues/737
Clarifies the purpose of the `MaxAge` field of the summary.

Improve description of MaxAge in summary docs

---

prometheus/collectors/dbstats_collector.go
prometheus/collectors/dbstats_collector_go115.go
prometheus/collectors/dbstats_collector_pre_go115.go
prometheus/collectors/dbstats_collector_test.go

Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>
This is redo of https://github.com/prometheus/client_golang/pull/848

Add collector for database/sql#DBStats

---

MAINTAINERS.md

Lazy consensus was already established among prometheus-team. This
change will be announced on prometheus-developers@ once it is merged.
@kakkoyun (just tagging you here for bootstrapping – once this is merged, I'll grant you the appropriate GH permissions, and then we can also assign you as a reviewer to a PR in this repo)

Change maintainers from @beorn7 to @bwplotka/@kakkoyun

---

prometheus/histogram.go
prometheus/summary.go

Document implications of negative observations

---

CHANGELOG.md

Address minor issues on the changelog

---

examples/random/main.go
go.mod
go.sum
prometheus/examples_test.go
prometheus/histogram.go
prometheus/histogram_test.go

This seem what OTel is converging towards, see
open-telemetry/oteps#149 .
I see pros and cons with base-10 vs base-2. They are discussed in
detail in that OTel PR, and the gist of the discussion is pretty much
in line with my design doc. Since the balance is easy to tip here, I
think we should go with base-2 if OTel picks base-2. This also seems
to be in agreement with several proprietary solution (see again the
discussion on that OTel PR.)
The idea to make the number of buckets per power of 2 (or formerly 10)
a power of 2 itself was also sketched out in the design doc
already. It guarantees mergeability of different resolutions. I was
undecided between making it a recommendation or mandatory. Now I think
it should be mandatory as it has the additional benefit of playing
well with OTel's …

Switch sparse histograms to base-2 buckets

---

prometheus/histogram.go
prometheus/histogram_test.go

This function calculates exponential buckets with different arguments
than the existing ExponentialBuckets function. Instead of specifying the
start and factor, the user can specify the min and max bucket value. We
have been doing it this way internally at my company for some time.

add ExponentialBucketsRange function

---

prometheus/histogram.go
prometheus/histogram_test.go

_This is merely a PR against the sparsehistogram branch._
@dieterbe @codesome Finally a more or less clean version of the bucket limitation strategy.

Implement strategy to limit the sparse bucket count

---

go.mod
go.sum

Brings in a fix for asm errors when dynamic linking with Go 1.17.
Fixes #912
Signed-off-by: David Trudgian <david.trudgian@sylabs.io>

Update cespare/xxhash dependency

---

examples/random/main.go

example/random: Move flags and metrics into main()

---

.circleci/config.yml
prometheus/collectors/dbstats_collector_go115.go
prometheus/collectors/dbstats_collector_pre_go115.go
prometheus/process_collector_other.go
prometheus/process_collector_test.go

This is a continuation of https://github.com/prometheus/client_golang/pull/911 which did not have any further activities. It fixes the go build lines that go 1.17 now prefers.

Add support for go 1.17

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Signed-off-by: Ben Ye <ben.ye@bytedance.com>
Support the WAL Replay Status API https://prometheus.io/docs/prometheus/latest/querying/api/#wal-replay-stats.
From the document, there should be another field `state`:
```
$ curl http://localhost:9090/api/v1/status/walreplay
{
"status": "success",
"data": {
"min": 2,
"max": 5,
"current": 40,
"state": "in progress"
}
}
```
But I cannot find it from the prometheus code https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L1375.

API: support wal replay status api

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

Current structs for v1 HTTP API assume that there is chunkCount and timeSeriesCount on /api/v1/status/runtimeinfo, which seems to be gone for at least a few releases. /api/v1/status/tsdb now holds an extra headStats block with chunkCount, numSeries and a few other fields.
Update API models and tests to reflect this change.
Signed-off-by: Łukasz Mierzwa <l.mierzwa@gmail.com>

Update /api/v1/status/tsdb to include headStats

---

prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go
prometheus/promhttp/option.go
prometheus/promhttp/option_test.go

promhttp: Check validity of method and code label values

---

prometheus/collector.go
prometheus/go_collector_go117.go
prometheus/go_collector_go117_test.go

Currently the Go 1.17 collector does not protect access to rmSampleBuf,
and Collect may be invoked concurrently. This change adds a mutex around
all uses of rmSampleBuf and pulls out operations that may block on
channels, so concurrent calls to Collect can at least pipeline those two
operations.
Fixes #968

Make the Go 1.17 collector thread-safe

---

prometheus/go_collector_go117.go
prometheus/go_collector_go117_test.go
prometheus/go_collector_test.go

A previous PR made it so that the Go 1.17 collector locked only around
uses of rmSampleBuf, but really that means that Metric values may be
sent over the channel containing some values from future metrics.Read
calls. While generally-speaking this isn't a problem, we lose any
consistency guarantees provided by the runtime/metrics package.
Also, that optimization to not just lock around all of Collect was
premature. Truthfully, Collect is called relatively infrequently, and
its critical path is fairly fast (10s of µs). To prove it, this test
also adds a benchmark.
Signed-off-by: Michael Anthony Knyszek <mknyszek@google.com>

Use simpler locking in the Go 1.17 collector

---

api/client.go
api/client_test.go

Replace `io.ReadAll` with `bytes.Buffer.ReadFrom`.
Both need to resize a buffer until they have finished reading; the former increases by 1.25x each time while the latter uses 2x.
(I considered using `ContentLength` to size the buffer, but empirically Prometheus does not set it on larger responses.)
Also added a benchmark to demonstrate the benefit:
```
name             old time/op    new time/op    delta
Client/4KB-8       35.9µs ± 4%    35.3µs ± 3%     ~     (p=0.310 n=5+5)
Client/50KB-8      83.1µs ± 8%    69.5µs ± 1%  -16.37%  (p=0.008 n=5+5)
Client/1000KB-8     891µs ± 6%     750µs ± 0%  -15.83%  (p=0.016 n=5+4)
Client/2000KB-8    1.74ms ± 2%    1.35ms ± 1%  -22.72%  (p=0.008 n=5+5)
name             old alloc/op   new alloc/op   delta
Client/4KB-8       20.2kB ± 0%    20.4kB ± 0% …
```

API client: make http reads more efficient

---

prometheus/gen_go_collector_metrics_set.go
prometheus/go_collector_go117.go
prometheus/go_collector_go117_test.go
prometheus/go_collector_metrics_go117_test.go
prometheus/internal/go_runtime_metrics.go

The Go runtime/metrics package currently exports extremely granular
histograms. Exponentially bucket any histogram with unit "seconds"
or "bytes" instead to dramatically reduce the number of buckets, and
thus the number of metrics.
This change also adds a test to check for expected cardinality to
prevent cardinality surprises in the future.
Fixes #967 
Signed-off-by: Michael Anthony Knyszek <mknyszek@google.com>

Reduce granularity of histogram buckets for Go 1.17 collector

---

.circleci/config.yml
README.md
go.mod

As requested in https://github.com/prometheus/common/pull/353#discussion_r793113705

go.mod: Set minimal support version of go to 1.15

---

prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go
prometheus/promhttp/option.go
prometheus/promhttp/option_test.go

Porting fix to 1.11 release.
* Check validity of method and code label values
* Use more flexibly functional option pattern for configuration
* Update documentation
* Simplify
* Fix inconsistent method naming

promhttp: Check validity of method and code label values (#962)

---

Dockerfile
examples/random/main.go

1. Update `examples/random/main.go`: `prometheus.NewBuildInfoCollector` is deprecated. Use `collectors.NewBuildInfoCollector` instead.

Fix deprecated `NewBuildInfoCollector` API

---

prometheus/examples_test.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/metric.go
prometheus/metric_test.go

Relates to #868. We're looking to add support for exemplars on OpenTelemetry's collector contrib's `prometheusexporter` which uses the `constHistogram` internally. This change solves the case where metrics coming from another system (in our case the otel collector) need to be converted to the Prometheus format and retain their exemplars. Right now we've only implemented exemplars on the const histogram, I'm more than happy to do all the necessary adjustments.

Add exemplar support for const histogram

---

prometheus/graphite/bridge.go
prometheus/graphite/bridge_test.go

When prefix is empty, no more dots should be written

---

api/prometheus/v1/api.go

Make apiClientImpl.DoGetFallback more idiomatic and efficient:
* Save result of args.Encode() operation as it might be used 2 times in
the function and due to looping and sorting it might be heavy.
* Follow line-of-sight practise and therefore simplify the code.

Refactor apiClientImpl.DoGetFallback

---

prometheus/push/push.go

Add PushContext and AddContext to Pusher, which are context-aware
version of Push and Add respectively.  They give a caller the ability
to cancel an HTTP request.

push: Add PushContext and AddContext to Pusher

---

api/prometheus/v1/api.go

Address #1020.
Signed-off-by: Tomáš Dohnálek <dohnto@gmail.com>
This was challenging to test. I used [toxiproxy](https://github.com/Shopify/toxiproxy) to inject connectivity issues. I build a [custom Toxic](https://github.com/Shopify/toxiproxy/blob/master/CREATING_TOXICS.md) which counts HTTP requests a closes every even request.
Without the header set, the conversation was following and my range query ended with
> Error querying Prometheus: Post "http://localhost:8080/api/v1/query_range": EOF
When I set the idempotency header, the conversation was equal to the case when GET is used - the connection is reopen and the request is retried.

Make Query requests idempotent

---

.circleci/config.yml
CHANGELOG.md
README.md
go.mod
prometheus/collectors/dbstats_collector_test.go

Based on request here by @kakkoyun https://github.com/prometheus/client_golang/pull/1027#pullrequestreview-939361219
@bwplotka One thing I saw was that the comment here says, this is supported since go 1.15, should we remove it as well? https://github.com/prometheus/client_golang/blob/main/prometheus/collectors/go_collector_go116.go#L45

Bump minimum required Go version to 1.16

---

CHANGELOG.md
prometheus/collectors/go_collector_latest.go
prometheus/go_collector_latest.go
prometheus/go_collector_latest_test.go

Fixes https://github.com/prometheus/client_golang/issues/967
I am not 100% sure we want this, but I would like to start this discussion.
On one hand, with @mknyszek we wanted new runtime/metrics naming and extra metrics to be exposed by default, so people can leverage it.
On the other hand:
* Honestly speaking some of those metrics are not useful for typical Go developers and SRE responsible for running Go services. They are pretty detailed for deeper debugging systems. We enabled opt-in of those in https://github.com/prometheus/client_golang/pull/1031 so anyone can use it, no need for it to be the default. We also need documentation and some learning path to even understand new naming and allow building dashboards and alerts with those.
* It adds ~80 new metrics to the total count (see …

gocollector: Reverted client_golang v1.12 addition of runtime/metrics metrics by default

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go
api/prometheus/v1/example_test.go

Update query API to support timeouts

---

prometheus/vec.go
prometheus/vec_test.go

Towards https://github.com/prometheus/client_golang/issues/834. This is an approach which I think feels user-friendly and accomplishes what folks were asking for. Open to suggestions of course, I'm new here.
This PR introduces a new deletion method:
- `DeletePartialMatch(labels Labels)` - deletes a metric if all of the given labels and associated values are present in that metric.
It returns the number of metrics which were deleted.

Implement deletion based on partially matching labels

---

.gitignore
CODE_OF_CONDUCT.md
README.md

There were still a few spots in this repository that used links with the old branch names. This PR fixes those links. The remaining two occurences of "master" are still up-to-date.

update branch names in a few links

---

prometheus/collectors/go_collector_latest_test.go
prometheus/go_collector_latest.go
prometheus/go_collector_metrics_go117_test.go
prometheus/go_collector_metrics_go118_test.go

Remove -Inf buckets from go collector histograms

---

CHANGELOG.md

Update readme after v0.12.2

---

prometheus/histogram.go
prometheus/histogram_test.go

_This is only going into the sparsehistogram branch._

Histogram: Fix bug with negative schemas

---

.circleci/config.yml
README.md
go.mod
go.sum

Update minimum supported Go to 1.17 to support new module format.
Signed-off-by: SuperQ <superq@gmail.com>

Update minimum supported Go version

---

prometheus/push/push.go

Background see: #1067 
@kakkoyun PTAL

Add Error API for pusher

---

prometheus/gen_go_collector_metrics_set.go

This also removes leftovers from merge conflicts that somehow made it into the release branch (but were never released, because the released commit wasn't in the release branch in the first place ;).

Merge commit tagged as v1.12.2 into the release branch

---

prometheus/counter_test.go
prometheus/value.go

In line with the OpenMetrics spec:
> The combined length of the label names and values of an Exemplar's LabelSet MUST NOT exceed 128 UTF-8 character code points
https://github.com/OpenObservability/OpenMetrics/blob/98ae26c87b/specification/OpenMetrics.md#exemplars
I suspect this number changed since the discussion in #706, but I can't see that change in the git history of the spec.

Raise exemplar labels limit from 64 to 128

---

api/prometheus/v1/api_test.go
prometheus/process_collector.go
prometheus/push/push.go
prometheus/push/push_test.go
prometheus/registry.go
prometheus/registry_test.go

`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>

Remove ioutil

---

prometheus/metric.go
prometheus/metric_test.go

Currently if there are exemplar values that are outside the maximum bucket bounds for a histogram metric, client_go lang will panic https://github.com/prometheus/client_golang/blob/main/prometheus/metric.go#L186-L189
When using this client in [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector), this panic leads to a crash and therefore we are unable to use client_golang in [prometheus exporter](https://github.com/Shopify/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter) in Open Telemetry Collector. There is a discussion about this issue in our [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9945) in that repository.
In this PR we are proposing a solution to this issue by explicitly adding `+inf` bucket when …

explicitly add +inf bucket in withExemplarsMetric

---

prometheus/metric.go
prometheus/metric_test.go

Additional fix on top of  https://github.com/prometheus/client_golang/pull/1094 see https://github.com/prometheus/client_golang/pull/1094#discussion_r931228577
Signed-off-by: bwplotka <bwplotka@gmail.com>

Fixed support for unordered input of exemplars.

---

prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_client_test.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go
prometheus/promhttp/option.go

Fixes: https://github.com/prometheus/client_golang/issues/854
Before merging:
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

Added exemplar support to http middleware.

---

.golangci.yml
api/client.go
api/prometheus/v1/api.go
api/prometheus/v1/api_test.go
prometheus/examples_test.go
prometheus/internal/difflib.go
prometheus/internal/difflib_test.go
prometheus/internal/go_runtime_metrics.go
prometheus/labels.go
prometheus/process_collector.go
prometheus/promhttp/http.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go
prometheus/push/push_test.go
prometheus/registry.go
prometheus/registry_test.go
prometheus/testutil/lint.go
prometheus/testutil/promlint/promlint.go
prometheus/testutil/testutil.go

This PR fixes a lot of the errors found by various linters in golangci-lint, mostly focussing on
* errorlint, ensuring errors are not compared with `==` or type assertions anymore, but `errors.Is()` and `errors.As()` are used.
* `strings.Replace(_, _, _, -1)` == `strings.ReplaceAll(_, _, _)`
* `string(buf.Bytes())` == `buf.String()`
* `if strings.HasSuffix(a, b) { trim suffix }` == `strings.TrimSuffix()`
* `reqParam` and `warnings` in the unit tests were entirely unused.
* I made the unit tests robust against people like me who trim spaces when saving a file. Previously some of the variables in the registry_test.go required trailing spaces in the Go code.

fix assorted oddities found by golangci-lint

---

prometheus/get_pid.go
prometheus/get_pid_gopherjs.go
prometheus/go_collector.go
prometheus/num_threads.go
prometheus/num_threads_gopherjs.go
prometheus/process_collector.go
prometheus/process_collector_js.go
prometheus/process_collector_other.go

When building against GopherJS, ThreadCreateProfile and Getpid are not available.
Return 1 to shim the functions.
Fixes "gopherjs build ./..."

Fix build against GopherJS

---

prometheus/collectors/go_collector_latest.go
prometheus/internal/go_collector_options.go

Signed-off-by: bwplotka <bwplotka@gmail.com>

Added compatibility mode with old options.

---

prometheus/collectors/go_collector_latest.go
prometheus/internal/go_collector_options.go

Signed-off-by: bwplotka <bwplotka@gmail.com>
Let's apply YAGNI and add that only when requested. It's not trivial code to be changed in bach Histogram to downsample buckets

Remove bucket option for now.

---

prometheus/collector.go
prometheus/collectors/go_collector_latest.go
prometheus/collectors/go_collector_latest_test.go

collectors/GoCollector: Add tests and examples

---

prometheus/collector.go
prometheus/collectors/go_collector_latest.go
prometheus/collectors/go_collector_latest_test.go
prometheus/go_collector.go
prometheus/go_collector_latest.go
prometheus/go_collector_latest_test.go
prometheus/internal/go_collector_options.go

Fixes: https://github.com/prometheus/client_golang/issues/1089
cc @mknyszek 
e,g to enable all runtime/metrics you can do this:
```
reg := prometheus.NewRegistry()
reg.MustRegister(NewGoCollector(
WithGoCollectorRuntimeMetrics(GoRuntimeMetricsRule{
Matcher: regexp.MustCompile("/.*"),
}),
))
```
TODO:
Signed-off-by: bwplotka <bwplotka@gmail.com>

collectors.GoCollector: Added rule support for granular metric configuration.

---

prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_client_test.go

Fixes #1117
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

Fix double-counting bug in promhttp.InstrumentRoundTripperCounter

---

prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_server.go

Fixes #1120 
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

Clarify exemplar(Add|Observe) by renaming to (add|observe)WithExemplar

---

prometheus/registry.go
prometheus/registry_test.go

This change allows Registries to be used as Collectors.
This enables new instances of Registry to be passed to ephemeral subroutines for collecting metrics from subroutines which are still running:
```go
package main
import (
"fmt"
"github.com/prometheus/client_golang/prometheus"
)
func main() {
globalReg := prometheus.NewRegistry()
for i := 0; i < 100; i++ {
workerReg := prometheus.WrapRegistererWith(prometheus.Labels{
// Add an ID label so registered metrics from workers don't
// collide.
"worker_id": fmt.Sprintf("%d", i),
}, prometheus.NewRegistry())
globalReg.MustRegister(workerReg)
go func(i int) {
runWorker(workerReg)
// Unregister any metrics the worker may have created.
globalReg.Unregister(workerReg)
}(i)
}
}
// runWorker runs a worker, registering worker-specific metrics.
func …
```

Extend prometheus.Registry to implement Collector

---

prometheus/promauto/auto.go

The wording of the documentation is slightly misleading. Before this
commit, it says that the returned collectors are "already registered".
This could be interpreted in two ways, one could think that promauto
keeps some sort of cache of already registered Collectors that are
returned by this package, and the other way is that the Collectors
constructed are registered before being returned. What is actually
happening is the latter, and the wording after this PR leaves no room to
think that the former could be the case.

Clarify documentation around what constructors do

---

examples/gocollector/main.go

Replace deprecated WithGoCollections with WithGoCollectorRuntimeMetrics in examples/gocollector folder
Signed-off-by: rogerogers <rogers@rogerogers.com>

Examples: replace deprecated WithGoCollections with WithGoCollectorRuntimeMetrics

---

prometheus/histogram.go
prometheus/metric.go
prometheus/metric_test.go

When writing histogram metrics, and there is an exemplar for the +Inf bucket, then the +Inf bucket is added with the value of the previous bucket.
This is incorrect, as the cumulative count of the +Inf bucket should instead be added with the total count of the histogram datapoint.
The above behaviour results in invalid values being reported for the +Inf bucket.
See issue: https://github.com/prometheus/client_golang/issues/1147
@bwplotka @kakkoyun

Fix `CumulativeCount` value of `+Inf` bucket created from exemplar

---

prometheus/counter.go

Potential fix for #1145.
Signed-off-by: Fabian Stäber <fabian@fstab.de>

Fix race condition with Exemplar in Counter

---

examples/random/main.go
examples/simple/main.go
prometheus/doc.go

I've updated the current examples under `/examples` to use a custom registry instead of the default one, in order to address https://github.com/prometheus/client_golang/issues/1101. 
I've changed also the basic example in https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#hdr-A_Basic_Example
I haven't updated yet the tests (e.g [here](https://github.com/prometheus/client_golang/blob/main/prometheus/examples_test.go#L42)) - maybe I can add them in a separate PR? 
cc @kakkoyun @bwplotka

Update examples to use custom registry

---

prometheus/histogram_test.go
prometheus/internal/almost_equal.go
prometheus/internal/difflib.go

Background
=========
Architectures using FMA optimization yield slightly different results so we cannot assume floating point values will be precisely the same across different architectures.
https://github.com/prometheus/client_golang/pull/899#issuecomment-1244506390
Change
======
The solution in this change is to check "abs(a-b) < tolerance" instead of comparing the exact values. This will give us confidence that the histogram buckets are near identical.
Testing
=====
I have not tested this change on one of the previously failing architectures. Help from someone with access to one of these architectures would be appreciated.

Fix float64 comparison test failure on archs using FMA

---

.circleci/config.yml
api/prometheus/v1/api.go
prometheus/counter.go
prometheus/doc.go
prometheus/gauge.go
prometheus/internal/difflib.go
prometheus/labels.go
prometheus/promauto/auto.go
prometheus/push/push.go
prometheus/summary.go
prometheus/timer.go

Fixes #1135
* Add update tests for new Go 1.19 metrics
* Format files using the latest formatter

Test and support 1.19

---

prometheus/histogram.go
prometheus/histogram_test.go

@dswarbrick could you try out if this PR fixes #1165 on ppc64le ?

Fix issue with atomic variables on ppc64le

---

prometheus/desc.go

This error is really hard to debug as it provides no dynamic context, and "duplicate label names" on it's own can provide confusion as to what the error is. I tried to include a little more context on "what the source of duplication was" as well as "what metric caused this" to help in debugging.

Add context to "duplicate label names" to enable debugging

---

prometheus/counter.go
prometheus/counter_test.go
prometheus/desc.go
prometheus/examples_test.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/labels.go
prometheus/registry.go
prometheus/summary.go
prometheus/value.go
prometheus/vec.go
prometheus/vec_test.go
prometheus/vnext.go
prometheus/wrap.go

Constrained variants of MetricVec provides a way to restrict the possible values a label can take, to prevent cardinality explosion when the label value comes from a non-trusted source (as a user input or HTTP header).
Extracted from discussions on #1066 
@bwplotka @kakkoyun

Add constrained labels and Constrained variant for all MetricVecs

---

prometheus/registry.go
prometheus/registry_test.go

Fixes #1137
- adds the metrics timestamp to the metric repetition validation hash
- adds a unit test for metric consistency check
Signed-off-by: João Vilaça <jvilaca@redhat.com>

Support for multiple samples within same metric

---

prometheus/counter_test.go
prometheus/desc.go
prometheus/go_collector_latest.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/metric.go
prometheus/metric_test.go
prometheus/registry.go
prometheus/registry_test.go
prometheus/summary.go
prometheus/value.go
prometheus/wrap.go
prometheus/wrap_test.go

This replaces usage of proto.{Float64,Int32,Int64,String,Uint32,Uint64}, which doesn't break the interface.
And remove usage of proto.MarshalTextString in wrap_test.go
Updates: #1175
Signed-off-by: Shengjing Zhu <zhsj@debian.org>

Replace deprecated github.com/golang/protobuf package

---

go.mod
go.sum

Bump golang.org/x/text to v0.3.8 to mitigate CVE-2022-32149

---

examples/simple/main.go
prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/instrument_server_test.go
prometheus/promhttp/option.go
prometheus/promhttp/option_test.go

Signed-off-by: Quentin Devos <4972091+Okhoshi@users.noreply.github.com>
I need to partition the metrics generated by promhttp by the value coming in a specific header, and while I appreciate the design of promhttp is made to be simple and cover only the base use cases, it would be great if we could have a bit more of flexibility.
It would also give a way to solve #491 elegantly while letting the user control the cardinality of the label they add.
@bwplotka  @kakkoyun

Add possibility to dynamically get label values for http instrumentation

---

prometheus/push/push.go
prometheus/push/push_test.go

Signed-off-by: songjiayang <songjiayang1@gmail.com>
issue #1065

Add `Header` method to Pusher for custom header

---

prometheus/doc.go
prometheus/promauto/auto.go

As in the title. This change will render example code indentation in godoc to be more consistent and then, therefore, make the code examples looks better.

Indent example in godoc consistently

---

prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_server.go

Remove unnecessary check if label is nil in observeWithExemplar

Remove unnecessary check if label is nil in observeWithExemplar

---

prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go

**Problem**:
Implementation for GatherAndCompare does not match documentation. Documentation says that if you provide any metricNames it filters both provided and expected metrics. But only provided metrics are filtered in `compareMetricFamilies` function.
Here is my **usecase**: https://github.com/fluxninja/aperture/blob/main/pkg/otelcollector/metricsprocessor/processor_test.go#L154
I manually add `<split>` in the expectedMetrics string so I don't have to provide multiple expectedMetrics variables.

Filter expected metrics as well in CollectAndCompare

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

The upstream prometheus HTTP API supports POSTS for these methods (the same as Query and QueryRange). Similar to the original issue (https://github.com/prometheus/client_golang/issues/428) we can hit 414 errors with these other APIs. This change simply duplicates the logic to these other endpoints
Related to: https://github.com/jacksontj/promxy/issues/588

Switch to POST for LabelNames, Series, and QueryExemplars to DoGetFallback

---

tutorial/whatsup/Makefile
tutorial/whatsup/internal/acceptance_test.go
tutorial/whatsup/internal/common.go
tutorial/whatsup/internal/playground_test.go

A bit of hacks for tutorial in order to make it work on killercoda.

Fixed tutorial.

---

go.mod
prometheus/example_metricvec_test.go
prometheus/examples_test.go

Switch tests over to new proto libary, eliminating the direct dependency on the old proto library. Note the indirect requirement is still needed due to upstream use by the client_model package.
Related: https://github.com/prometheus/client_golang/issues/1175

Cleanup proto use in tests

---

prometheus/promhttp/instrument_client.go
prometheus/promhttp/instrument_server.go
prometheus/promhttp/option.go

Unfortunately optionality is important as not every e.g. ObserverVec implements exemplar (e.g. summary).
For counters this is not that needed - but changed for consistency and readability.

Fixed promhttp Instrument* handlers.

---

tutorial/whatsup/internal/common.go

@bwplotka I noticed while doing the tutorial on a WSL2 based system the application URL generated is invalid. This fix aims to detect whether its being ran on a WSL-based system and if so, gets the IPv4 address of `eth0` and uses that as the 'whatsup' address in the Prometheus configuration.

Fix tutorial on WSL-based systems

---

api/prometheus/v1/api.go

This PR fixes instances of undefined execution order in return statements, which is described in [https://github.com/golang/go/issues/58233](https://github.com/golang/go/issues/58233).
Fixes #1259

Fix undefined execution order in return statements

---

.github/workflows/golangci-lint.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

prometheus/promhttp/http.go

This PR adds an option to enable a header to return process start time in a header.
This allows a scraping agent to avoid buffering the entire response body in memory until process_start_time_seconds is reached.

add process start time header to client_golang prometheus

---

prometheus/histogram.go
prometheus/histogram_test.go

The current code doesn't work fork negative schemas if the observed
value should go into a bucket with a non-positive key.
In the 1st commit, tests are added to expose the bug.
In the 2st commit, the bug is fixed. The expression smells a bit like it should be possible to simplify. But I couldn't come up with a simpler form. Let me know if you have any ideas.

Fix bug in bucket key calculation

---

.github/workflows/Circle-ci.yml

Signed-off-by: Krishna Dutt Panchagnula <krishnadutt123@gmail.com>
closes #1280

added circleci as gh action YAML

---

prometheus/testutil/promlint/promlint.go

This linter was implemented in the ci test for kubevirt operators, see:https://github.com/kubevirt/monitoring/tree/main/test/metrics/prom-metrics-linter. 
As part of this implementation we found (we think) a better way for the metricUnits function.
We tested this function runtime in both cases using "testing", and the runtime for this pr is much shorter. we're using random access to query the map, instead of looping over it again and again. see:
current version named `metricUnits` and the suggested version named `metricUnits2`
```
BenchmarkMetricUnits
BenchmarkMetricUnits/metricUnits
BenchmarkMetricUnits/metricUnits-16         	  106170	     11550 ns/op
BenchmarkMetricUnits/metricUnits2
BenchmarkMetricUnits/metricUnits2-16        	 7445168	       160.4 ns/op
BenchmarkMetricUnits2 …
```

Improve metricUnits runtime

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yml

ci: define minimal permissions to GitHub workflows

---

prometheus/benchmark_test.go
prometheus/counter.go
prometheus/desc.go
prometheus/examples_test.go
prometheus/expvar_collector.go
prometheus/gauge.go
prometheus/gauge_test.go
prometheus/histogram.go
prometheus/labels.go
prometheus/promhttp/http_test.go
prometheus/registry.go
prometheus/summary.go
prometheus/value.go
prometheus/vec.go

Implementing a fast path when there's no constrained label should limit a lot the number of allocations.
Closes #1276

Do not allocate memory when there's no constraints

---

prometheus/histogram.go
prometheus/histogram_test.go

Fixes #1127.
If a native histogram has no observations and a zero threshold of
zero, then it is indistinguishable from a classic histogram. To give
scrapers a hint that it is indeed a native histogram, we add a no-op
span.
This needs follow-up PRs in prometheus/prometheus and
prometheus/client_model.
(The 1st commit is just a cleanup of doc comments and long lines.)

histogram: Enable detection of a native histogram without observations

---

go.mod
go.sum
prometheus/counter_test.go
prometheus/example_metricvec_test.go
prometheus/examples_test.go
prometheus/expvar_collector_test.go
prometheus/gauge_test.go
prometheus/histogram_test.go
prometheus/registry_test.go
prometheus/utils_test.go
prometheus/wrap_test.go

Opening this PR to make the review of https://github.com/prometheus/client_golang/pull/1313 easier.
This one is only about bumping the version of client_model in go.mod. This version upgrade is particularly difficult because, in client_model, it updates the version of protoc which changes how proto messages are cast into strings:
1. '<' and '>' characters were replaced with '{' and '}' respectively.
2. The text format is non-deterministic. More information in https://github.com/golang/protobuf/issues/1121
3. proto3 adds a new field to proto.Message(sizeCache) that breaks `reflect.DeepEqual`. Forcing us to use `proto.Equal` now.

Bump client_model

---

prometheus/histogram.go

I was a bit confused by this "inaccuracy" (?), WDYT?

histogram docs: Fixed minor nit.

---

go.mod
go.sum
prometheus/counter.go
prometheus/counter_test.go
prometheus/example_metricvec_test.go
prometheus/examples_test.go
prometheus/expvar_collector_test.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/metric.go
prometheus/registry_test.go
prometheus/summary.go
prometheus/summary_test.go
prometheus/utils_test.go
prometheus/value.go
prometheus/value_test.go
prometheus/wrap_test.go

Following our [design doc](https://docs.google.com/document/d/1kakDVn8aP1JerimLeazuMfy2jaB14W2kZDHMRokPcv4/edit), this PR aims to add created timestamp to counters, summaries, and histograms when using Prometheus protobuf.

Extend Counters, Summaries and Histograms with creation timestamp

---

prometheus/collectors/go_collector_latest.go

This PR changes comments for deprecated functions and consts. From the https://go.dev/blog/godoc:
> To signal that an identifier should not be used, add a paragraph to its doc comment that begins with “Deprecated:” followed by some information about the deprecation.
Without PR's change:
With change:

Deprecated comment should begin with "Deprecated:"

---

prometheus/labels.go

The slice with variadic arguments passed to MetricVec.WithLabelValues() was escaping to heap. This change fixes that by performing a copy of the slice before passing it to fmt.Errorf(), which is where the slice was escaping. This keeps the hot path without that allocation.
Meaningful benchmark results (skipping ~0 CPU and 0 alloc ones):
```
│    old.txt    │               new.txt                │
│    sec/op     │    sec/op     vs base                │
Counter/With_Label_Values-16                                     108.00n ±  6%   58.06n ±  1%  -46.24% (p=0.000 n=10)
Counter/With_Label_Values_and_Constraint-16                       174.5n ± 15%   136.8n ±  6%  -21.63% (p=0.000 n=10)
Counter/With_triple_Label_Values-16                               309.3n ± 12%   172.9n ±  1%  -44.08% …
```

Improve performance of WithLabelValues(...)

---

prometheus/process_collector_other.go
prometheus/process_collector_wasip1.go

This resolves build failures like this when using the wasip1 support:
../../../go/pkg/mod/github.com/prometheus/procfs@v0.11.1/fs_statfs_type.go:25:18: undefined: syscall.Statfs_t
../../../go/pkg/mod/github.com/prometheus/procfs@v0.11.1/fs_statfs_type.go:26:17: undefined: syscall.Statfs
See https://go.dev/blog/wasi.

proccess_collector: add wasip1 stub

---

prometheus/histogram.go
prometheus/histogram_test.go

Fixes #1248. See issue description for all the details.

histograms: Add timer to reset ASAP after bucket limiting has happened

---

prometheus/examples_test.go

Fixes #1364
Adds an example for NewConstMetricWithCreatedTimestamp.

Add example of NewConstMetricWithCreatedTimestamp

---

prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go

Due to an inconsistency in the text protocol between encoding and decoding, it was not possible to use the `testutil.CollectAndCompare` function to test metrics with empty help values. To fix this, normalize empty help values from the expected/want side of the test so that they compare correctly with empty values on the actual/got side of the test.
Fixes #1308.

Normalize empty help values in CollectAndCompare

---

api/client.go
api/client_test.go

Hi there,
The current implementation uses http.Client
The only function which is called for it is `Do(req *http.Request) (*http.Response, error)`
It is desirable to allow other Client implementations, e.g. `github.com/hashicorp/go-retryablehttp/Client` which allows retries on various HTTP status codes like 429 (it has its own `Request` struct but it's easy to wrap it in another struct that will implement the above-mentioned interface). Many commercial solutions implementing Prometheus API (e.g. Grafana Cloud) have rate limiting. Thank you.

change api http.client to interface

---

api/client.go
api/client_test.go

Hi,
Thanks @ArthurSens and @tips for doing the work! However, I think the #1387  change might not be necessary. I explained in https://github.com/prometheus/client_golang/pull/1387#pullrequestreview-1794338682 --let me know if this makes sense. I think we could update the docs to make it more clear.
TL;DR One can achieve the use case mentioned by @tips in many ways currently
```
api.Confg{Config: retryablehttp.StandardClient(}}
```
or
```
api.Confg{Config: &http.Client{Transport: <Your method with (*Request) (*Response, error) semantics>}}
```
Let's avoid additional interfaces which looks 99.999% like standard library ones and avoid allowing multiple ways of doing the same thing.

Revert "change api http.client to interface"

---

version/version.go

Migrate the `version` package from `github.com/prometheus/common` to `github.com/prometheus/client_golang` in order to break the circular dependency.
* Make `version` a top level package because it uses `init()` to populate data.
Related to: https://github.com/prometheus/common/issues/58

Add version package

---

.github/dependabot.yml
.github/workflows/automerge-dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/golangci-lint.yml

Closes #1416
As mentioned on the issue, this PR enhances project security by hash-pinning the dependencies that are called under dangerous permissions and configuring dependabot to automatically update them. Additionally, I've also used this PR to contribute with the nit-pick I've mentioned on commentaries at #1294; those changes will ensure all workflows are running with minimal permissions.
I configured dependabot in a way that all of version updates will be collapsed in a single PR sent monthly -- this avoids noisy PRs, which is a common concern haha. Regardless of the frequency chosen, for the case of security updates a PR with the fixed version would be sent right away.

CI: Hash pin all GH actions + configure dependabot for those.

---

.github/workflows/go.yml
Makefile
README.md
go.mod
prometheus/histogram_test.go
prometheus/summary_test.go

We promise support for the latest 3 major versions of go. With #1445 merged, support for 1.19 is no longer promised.
In addition, the latest release of prometheus/common uses a function only present in go 1.20 (See [workflow logs](https://github.com/prometheus/client_golang/actions/runs/8017443782/job/21901319988?pr=1447) from PR #1447), meaning that we can't upgrade common without bumping our go version.

Remove support for go 1.19

---

go.mod
go.sum
prometheus/push/push.go
prometheus/push/push_test.go
prometheus/registry_test.go
prometheus/testutil/promlint/promlint.go
prometheus/testutil/testutil.go

Fixes https://github.com/prometheus/client_golang/issues/1446

deps: bump prometheus/common version

---

CHANGELOG.md

Stating that it was a bug sounds like the change made upstream was accidental and due to a mistake.
The change was intentional, so let's rephrase our changelog :)

Rephrase incompatibility with common v0.48.0

---

prometheus/testutil/promlint/promlint_test.go
prometheus/testutil/promlint/validations/duplicate_validations.go

This is from https://github.com/prometheus/prometheus/pull/5312; the code moved to this repo since that PR was opened.
@geekodour is the original author.

Add LintDuplicateMetric to promlint

---

prometheus/promhttp/delegator.go
prometheus/promhttp/delegator_test.go

According to https://pkg.go.dev/net/http#NewResponseController
If the `ResponseWriter` implements any of the following methods, the `ResponseController` will call them as appropriate:
```
Flush()
FlushError() error // alternative Flush returning an error Hijack() (net.Conn, *bufio.ReadWriter, error)
SetReadDeadline(deadline time.Time) error
SetWriteDeadline(deadline time.Time) error
EnableFullDuplex() error
```
If the `ResponseWriter` doesn't implement the methods, the `ResponseController` will call `Unwrap()` method until it finds a ResponseWriter in the chain, according to https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/net/http/responsecontroller.go;l=73
This commit implements `Unwrap()` method to simply return the wrapped `ResponseWriter`

Implement Unwrap() for responseWriterDelegator

---

.github/workflows/go.yml

Currently, go.yml file contains hardcoded list of [supported Go versions](https://github.com/prometheus/client_golang/blob/e38b67e77a6969b0c660691e1a7d29404c24dcfb/.github/workflows/go.yml#L21). This needs to be manually updated when a new Go version is available.
With this PR, this list will be fetched from [supprted_go_versions.txt](https://github.com/prometheus/client_golang/blob/e38b67e77a6969b0c660691e1a7d29404c24dcfb/supported_go_versions.txt) (only the latest 3 Go versions). 
Related PR: https://github.com/prometheus/client_golang/pull/1481

ci: Remove hardcoded supported Go versions from go.yml

---

prometheus/collectors/gen_go_collector_set.go
prometheus/collectors/go_collector_go120_test.go
prometheus/collectors/go_collector_go121_test.go
prometheus/collectors/go_collector_go122_test.go

A small refactoring to how base metrics are added to scheduler metrics.
I've noticed that this could be simplified while working on https://github.com/prometheus/client_golang/pull/1389. Some changes will conflict with the mentioned PR, but I'll solve them once one of them is merged :)
cc @SachinSahu431 @kakkoyun

chore: Refactor how base metrics are added to Sched metrics

---

prometheus/collectors/gen_go_collector_set.go
prometheus/collectors/go_collector_go117_test.go
prometheus/collectors/go_collector_go119_test.go
prometheus/collectors/go_collector_go120_test.go
prometheus/collectors/go_collector_latest.go
prometheus/collectors/go_collector_latest_test.go

At the same time, it also solves the linting problem we're getting on main

gocollector: Add regex option to allow collection of debug runtime metrics

---

.github/workflows/automerge-dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/go.yml
.github/workflows/golangci-lint.yml

fixes https://github.com/prometheus/client_golang/issues/1437
- Whenever we push commits to a PR, workflows are triggered for that commit. After that, if we push additional commits to this PR, workflows in Github Actions run on both commits.
- We need to cancel the previous run and run only on the most recent pushed commit. This would help save some GitHub Action Minutes (probably not a problem for this project but its always better to same some resources) and unexpected workflow failures on previous commits.

[CI]: Add Concurrency Grouping to GitHub Workflows

---

prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go

CollectAndFormat is a helper function that returns the formatted metrics to the caller, allowing them to use it how they want. This is different to CollectAndCompare where the comparison is done strictly on behalf of the caller. Often it is more convenient to perform a simple substring match on the formatted metric rather than the full export. This is especially true testing a duration-like gauge metric, where the exact value of the metric might not be easily determined up front.

Add CollectAndFormat to testutil, allowing caller to assert as they want to on the exported metric 

---

prometheus/testutil/testutil.go
prometheus/testutil/testutil_test.go

The functions `GatherAndCompare`, `ScrapeAndCompare` and others that use
`compareMetricFamilies` under the hood can return no error if
`metricNames` includes none of the names found in the scraped/gathered
results. To avoid false Positves (an error being the negative case), we
can return an error if there is is at least one name in `metricNames`
that is not in the filtered results.
Fixes: https://github.com/prometheus/client_golang/issues/1351
Signed-off-by: leonnicolas <leonloechner@gmx.de>

testutil compareMetricFamilies: make less error-prone

---

prometheus/metric.go

use  time.IsZero() for test time instance not set, replace code ' t = time.Time{}' make code more readable;  @ArthurSens @bwplotka @kakkoyun
golang doc for IsZero()

improved code more clean use time.IsZero() replace t = time.Time{}  

---

prometheus/histogram.go
prometheus/histogram_test.go

add native histogram exemplar support

---

.github/workflows/pr-auto-label.yml

I've noticed that we added the labeling workflow with several different CI jobs that depend on each other to run sequentially.
This dependency upon each other suggests that we might not want to run them as separate jobs.
This PR just groups them together, which makes them run sequentially by default :)
/kind release-note-none
```release-note
NONE
```

ci: Group all changelog-related CI jobs into single one

---

.github/workflows/pr-auto-label.yml

Remove synchronize trigger from changelog automation workflow. 
Related https://github.com/prometheus/client_golang/pull/1496#issuecomment-2145363857
/kind release-note-none
```release-note
NONE
```

Remove synchronize trigger from changelog workflow

---

go.mod
go.sum
internal/github.com/golang/gddo/LICENSE
internal/github.com/golang/gddo/README.md
internal/github.com/golang/gddo/httputil/header/header.go
internal/github.com/golang/gddo/httputil/header/header_test.go
internal/github.com/golang/gddo/httputil/negotiate.go
internal/github.com/golang/gddo/httputil/negotiate_test.go
prometheus/promhttp/http.go
prometheus/promhttp/http_test.go

This allows endpoints to respond with zstd compressed metric data, if the requester supports it. For backwards compatibility, gzip compression will take precedence.
I added a benchmark to the http_test.go, that will test with a differently sized synthetic metric series.
```
Running tool: go test -benchmem -run=^$ -bench ^BenchmarkEncoding$ github.com/prometheus/client_golang/prometheus/promhttp
goos: linux
goarch: amd64
pkg: github.com/prometheus/client_golang/prometheus/promhttp
cpu: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
BenchmarkEncoding/test_with_gzip_encoding_small-8         	   20670	     53641 ns/op	  111770 B/op	      49 allocs/op
BenchmarkEncoding/test_with_zstd_encoding_small-8         	    7838	    178033 ns/op	 1121493 B/op	      75 allocs/op …
```

feat: Support zstd compression

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

This PR adds an option to client APIs to specify limit query parameters for APIs that support it.
For example, APIs, such as [Finding series by label matchers](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers), support optional query param:
- limit=<number>: Maximum number of returned series. 
However, the current  [client interface](https://github.com/prometheus/client_golang/blob/main/api/prometheus/v1/api.go#L492) provides no way to pass that parameter.
To minimize the impact on existing users of that client interface, this parameter is implemented as an existing optional argument. 
/kind enhancement
```release-note
Client APIs support extra arguments to specify limit query parameters for APIs that support it.
```

client: Add Option to provide limit query param for APIs that support it

---

prometheus/examples_test.go
prometheus/histogram.go
prometheus/histogram_test.go
prometheus/summary.go
prometheus/summary_test.go

Closes #1535
Currently there's no way to set created timestamp when creating constant histogram and summar metrics. This adds some new functions using the same naming as the existing `NewConstMetricWithCreatedTimestamp`
/kind enhancement
```release-note
api: Allow setting created timestamp on constant histogram and summary metrics using the new functions `NewConstHistogramWithCreatedTimestamp` and `NewConstSumamryWithCreatedTimestamp`
```
Verified locally that zero-injection happens for the _bucket, _sum, and _count series. An example:

Allow creating constant histogram and summary metrics with a created timestamp

---

prometheus/collectors/go_collector_latest_test.go
prometheus/go_collector.go

The context and details for help were possible thanks to @vesari research, thanks for that!
cc @vesari

go collector: add default metrics acceptance tests; adding more context to HELP

---

CHANGELOG.md
prometheus/collectors/go_collector_latest.go
prometheus/collectors/go_collector_latest_test.go
prometheus/go_collector.go

I know we ideally should not remove any metric from default list, but this one is always zero, so let's save everyone's money.

Remove go_memstat_lookups_total; added runtime/metrics calculation to memstat metric's help.

---

prometheus/go_collector_latest.go

This helps in filtering capabilities and generally in discovery/knowledge sharing.

gocollector: Attach original runtime/metrics metric name to help.

---

dagger.json

this commit also adds an `includes` field to the dagger.json so the initial SDK code generation runs faster as only the Dagger module source is included

ci: bump dagger to the latest version

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/container_description.yml
.github/workflows/dagger-golangci-lint.yml
.github/workflows/go.yml
.github/workflows/update-go-versions.yml
dagger/main.go
tutorials/whatsup/go.mod

* Update dagger actions to use pinnning.
* Add /dagger to dependabot to keep the Dagger modules up-to-date.
* Update dagger default Go version.
* Update tutorials/whatsup Go version.
* Update actions to use pinning.

Update Dagger and build.

---

examples/gocollector/main.go

examples: Improved GoCollector example.

---

api/client.go

when high concurrency occurs, the connection is full and the connection is rejected.

:zap: http client defer CloseIdleConnections

---

prometheus/histogram.go
prometheus/histogram_test.go

Fixes: #1607 
Fixes: #1605 
fix: native histogram: Simplify and fix addExemplar
mdIdx was redundant when len(exemplars)>1, so got rid of it, rIdx
is enough.
Don't compare timestamp of incoming exemplar to timestamp of
minimal distance exemplar. Most of the time the incoming exemplar
will be newer. And if not, the previous code just replaced an
exemplar one index after the minimal distance exemplar. Which had
an index out of range bug, plus is essentially random.
Contains an unoptimized fix for #1605 , see discussion / fix in #1609 
```
panic: runtime error: index out of range [10] with length 10
goroutine 10 [running]:
github.com/prometheus/client_golang/prometheus.(*nativeExemplars).addExemplar(0xc0002307c8, 0xc00055f4f0)
/home/krajo/go/github.com/krajorama/client_golang/prometheus/histog …
```

bugfix: native histogram: exemplars index out of range

---

CHANGELOG.md
prometheus/histogram.go

Follow-up to #1608
Fixes
```
2024-09-06T08:32:44.9910707Z 08:29:59 ingester-3: WARNING: DATA RACE
2024-09-06T08:32:44.9911367Z 08:29:59 ingester-3: Read at 0x00c001b9f4d8 by goroutine 480:
2024-09-06T08:32:44.9912309Z 08:29:59 ingester-3: github.com/prometheus/client_golang/prometheus.(*histogram).Write()
2024-09-06T08:32:44.9913404Z 08:29:59 ingester-3: /__w/mimir/mimir/vendor/github.com/prometheus/client_golang/prometheus/histogram.go:849 +0x16ef
2024-09-06T08:32:44.9914502Z 08:29:59 ingester-3: github.com/prometheus/client_golang/prometheus.(*wrappingMetric).Write()
2024-09-06T08:32:44.9915647Z 08:29:59 ingester-3: /__w/mimir/mimir/vendor/github.com/prometheus/client_golang/prometheus/wrap.go:172 +0x65
2024-09-06T08:32:44.9916698Z 08:29:59 ingester-3: …
```

native histogram: Fix race between Write and addExemplar

---

prometheus/process_collector_cgo_darwin.c
prometheus/process_collector_cgo_darwin.go
prometheus/process_collector_darwin.go
prometheus/process_collector_nocgo_darwin.go

This is built on top of the much easier to get process metrics in [PR1600](https://github.com/prometheus/client_golang/pull/1600), so only the last commit is interesting here (and the commit message has more details).  I don't expect or want this to be landed as-is, but am posting it here to help with any discussion about finishing off https://github.com/prometheus/client_golang/issues/1590.
I've not paid much attention to the RSS values of Go processes on macOS, but after ~5 minutes of banging on my own exporter with `curl`, I only ever see the value going up.  The values agree with the `ps` command.  There should be ~0 code other than from this module running, but we'll see what happens.
@bwplotka

process_xxx_memory statistics for macOS (cgo)

---

examples/createdtimestamps/main.go
prometheus/promhttp/http.go

This PR adds an extra option to print _created lines when OpenMetrics is the chosen exposition format. It's implemented following the conditional option added in https://github.com/prometheus/common/pull/504.

Optionally print OM created lines

---

api/prometheus/v1/example_test.go

Add example for NewHeadersRoundTripper implementation. 
fixes - https://github.com/prometheus/client_golang/issues/1653

test add headers round tripper

---

prometheus/metric.go

The BuildFQName function is used on many exporters multiple times.
The overall benefit might be quite low, but the I'm happy to contribute an optimization.
`strings.Builder` is available since go 1.10 and should me the current requirements.
```
% benchstat BenchmarkBuildFQName1.txt BenchmarkBuildFQName2.txt                                             
goos: darwin
goarch: amd64
pkg: github.com/prometheus/client_golang/prometheus
cpu: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
│ BenchmarkBuildFQName1.txt │      BenchmarkBuildFQName2.txt      │
│          sec/op           │   sec/op     vs base                │
BuildFQName1-8                 60.43n ± 0%   45.05n ± 0%  -25.44% (p=0.000 n=20)
BuildFQName2-8                 2.310n ± 1%   2.333n ± 1%   +1.00% (p=0.038 n=20)
BuildFQName3-8 …
```

Optimize BuildFQName function

---

prometheus/summary.go
prometheus/summary_test.go

Hi!
This PR should fix #1666
When you run `go test -run TestSummaryDecay` normally on laptop it is always pass. 
```
=== RUN   TestSummaryDecay
--- PASS: TestSummaryDecay (0.00s)
PASS
```
But on CI it (sometimes) fails.
```
--- FAIL: TestSummaryDecay (1.17s)
summary_test.go:396: 170. got 102.000000, want 80.000000
summary_test.go:396: 180. got 112.000000, want 90.000000
```
Looks like it takes very performance constrained environment to reveal problem. Lets recreate one.
Run something like `stress -c 14` and while it running execute `go test -run TestSummaryDecay` again:
```
=== RUN   TestSummaryDecay
summary_test.go:396: 220. got 166.000000, want 130.000000
summary_test.go:396: 230. got 181.000000, want 140.000000
summary_test.go:396: 240. got 197.000000, want 150.000000 …
```

fix: use injected now() instead of time.Now() in summary methods

---

prometheus/process_collector_cgo_darwin.c

The header has a warning when included, with no way to shut it off, and no alternative to obtain these symbols.  They're technically architecture specific values, but they aren't different between amd64 and arm64, so combine the definitions.
@bwplotka

process_collector: avoid a compiler warning on macOS (fixes #1660)

---

.golangci.yml
api/prometheus/v1/api_test.go
examples/exemplars/main.go
examples/random/main.go
prometheus/counter_test.go
prometheus/internal/difflib.go
prometheus/process_collector_cgo_darwin.go
prometheus/promhttp/http_test.go
prometheus/registry_test.go
prometheus/testutil/promlint/promlint_test.go
prometheus/testutil/promlint/validations/duplicate_validations.go
prometheus/value_test.go
prometheus/vec_test.go

[perfsprint](https://golangci-lint.run/usage/linters/#perfsprint) checks that fmt.Sprintf can be replaced with a faster alternative.

[chore]: enable perfsprint linter

---

prometheus/histogram.go
prometheus/histogram_test.go

This changes were supposed to be merged in #1662 but after some git manipulations it closed itself.
Here clean version of it.

Duplicate of #1662

---

.golangci.yml
prometheus/promhttp/http_test.go
prometheus/promhttp/instrument_client_test.go
prometheus/promhttp/instrument_server_test.go
prometheus/registry_test.go

[usestdlibvars](https://golangci-lint.run/usage/linters/#usestdlibvars) detect the possibility to use variables/constants from the Go standard library.

chore: enable usestdlibvars linter

---

prometheus/atomic_update.go
prometheus/atomic_update_test.go
prometheus/counter.go
prometheus/gauge.go
prometheus/histogram.go
prometheus/process_collector_cgo_darwin.go
prometheus/summary.go

Hi! 
This kind of issues: https://github.com/cockroachdb/cockroach/issues/133306 pushed me to investigate if it is possible to optimize client metrics library in terms of CPU and performance especially under contention. So mostly this PR is about that.
Add sort of exponential backoff for tight loops on CAS operations, which potentially will decrease contention and as a result will lead to better latencies and lower CPU consumption. This is well known trick that is used in many projects that deal with concurrency.
In addition this logic was refactored into single place in code because case of atomic update of float64 can be meet in different parts of the codebase.
All test results are from AWS c7i.2xlarge type of instance.
main vs proposed for histograms:
```
goos: linux
goarch: amd64
pkg: …
```

Add: exponential backoff for CAS operations on floats

---

prometheus/histogram.go
prometheus/histogram_test.go

Fixes: #1617 
Add exported ConstNativeHistogram - this can be used to build native histograms if one already has the relevant data without calling the observe function. A viable use case is while converting exponential histograms to nativehistograms.

[1617] Add ConstnativeHistogram

---

prometheus/process_collector_darwin.go

```shell
prometheus/process_collector_darwin.go:28:25: fmt.Errorf can be replaced with errors.New (perfsprint)
var notImplementedErr = fmt.Errorf("not implemented")
```

fix: replace fmt.Errorf with errors.New

---

prometheus/histogram_test.go

Test `TestHistogramAtomicObserve` taking too long to complete after introducing [this](https://github.com/prometheus/client_golang/pull/1661) change:
```
=== RUN   TestHistogramAtomicObserve
--- PASS: TestHistogramAtomicObserve (487.82s)
```
@ywwg pointed out that increase for this test runtime were introduced after adding exponential back-off to histograms.
If we will take a look at this test closely we will see that observations here
```go
for {
select {
case <-quit:
return
default:
his.Observe(1)
}
}
```
introduced in a very high pace inside tight loop without any delay or limit.
*  With multiple goroutines failing CAS operations and backing off, they sleep for significant amounts of time. 
* This leads to longer wait times for the `waitForCooldown` function in the `Write` method, as …

fix: add very small delay between observations in `TestHistogramAtomicObserve`

---

prometheus/promhttp/http.go

Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.

update links to openmetrics to reference the v1.0.0 release

---

Makefile
api/prometheus/v1/remote/genproto/v2/types.pb.go
api/prometheus/v1/remote/genproto/v2/types_vtproto.pb.go
api/prometheus/v1/remote/remote_api.go
api/prometheus/v1/remote/remote_api_test.go
api/prometheus/v1/remote/remote_headers.go

Addresses a few comments from PR
Also imports v1, as a convenience package as well (we can keep until we deprecate fully?)
Also makes Write marshaling more flexible with any type and gogo marshaling. Generics don't really seem to fit as you can't have multiple interface constraints on them.
Might be worth, merging with merge commit to keep original PR commits clear
cc: @bwplotka

Make Write message type more flexble, address some feedback

---

go.mod
go.sum
prometheus/counter_test.go
prometheus/internal/go_runtime_metrics.go
prometheus/promhttp/instrument_server_test.go
prometheus/push/push_test.go
prometheus/wrap_test.go

common 0.62.0 switches NameValidationScheme global variable to UTF8Validation. While relaxing validation this will likely yield test failures downstream.
It's unfortunate, but the alternatives were worse: https://github.com/prometheus/common/pull/724
Good news is that client_golang should work with older common deps and callers can easily change model.NameValidationScheme value to old value to solve any compatibility issues.

Upgrade to prometheus/common 0.62.0 with breaking change

---

prometheus/process_collector_cgo_darwin.go
prometheus/process_collector_darwin.go
prometheus/process_collector_nocgo_darwin.go

Errors:
```
* collected metric process_resident_memory_bytes gauge:{value:8.798208e+06} with unregistered descriptor Desc{fqName: "process_resident_memory_bytes", help: "Resident memory size in bytes.", constLabels: {}, variableLabels: {}}
* collected metric process_virtual_memory_bytes gauge:{value:4.2175053824e+11} with unregistered descriptor Desc{fqName: "process_virtual_memory_bytes", help: "Virtual memory size in bytes.", constLabels: {}, variableLabels: {}}
```

process collector: Fixed pedantic registry failures on darwin with cgo.

---

RELEASE.md
prometheus/collectorfunc.go
prometheus/collectorfunc_test.go
prometheus/examples_test.go

Resolves #1701 
- Added a new `CollectorFunc` utility in `promethues` package.
- Instead of having boilerplate code which consisted of explicit `Collect` and `Describe` functions, `CollectorFunc` just requires to have `Collect` logic in it. Thus reducing extra `boilerplate` code (under certain scenerios)
- Message to `CollectorFunc` function that it leverages the `DescribeByCollector` function
- Added test: `collectorfunc_test.go` (more test might be needed)
- Ran an example code with CollectorFunc and without it
cc: @bwplotka

feat: Add new CollectorFunc utility

---

api/prometheus/v1/api.go

* `WithLookbackDelta` and `WithStats` options have been added to API client.
* `lookback_delta` can be especially handy when dealing with mix of continuous and intermittent time series.

Add support for undocumented query options for API

---

exp/api/remote/remote_api.go
exp/api/remote/remote_api_test.go
exp/api/remote/remote_headers.go

This PR adds an accepted message arg to NewHandler, to allow callers to limit what remote write messages their servers can handle.

exp/api: Add accepted msg type validation to handler

---

prometheus/promhttp/http.go
prometheus/promhttp/http_test.go
prometheus/promhttp/internal/compression.go
prometheus/promhttp/zstd/zstd.go

This PR is a proof of concept for package isolation discussed in https://github.com/kubernetes/kubernetes/pull/130569#discussion_r1981503174
Eventually, zstd support is expected in the Go stdlib, but until then, making zstd support optional lets downstream consumers decide if they want to vendor / link the ~28kloc go+assembly klauspost/compress library into their build or not.
This _does_ change default behavior for library consumers who would now have to opt into zstd support, so I'll let the client_golang maintainers decide if that's acceptable, and if so, how best to manage that change.
xref discussion at https://github.com/prometheus/client_golang/pull/1496/files#r1717633170 as well when this was introduced

promhttp: Isolate zstd support and klauspost/compress library use to promhttp/zstd package

---

api/prometheus/v1/example_test.go

Replace demo URL with updated official demo site.

Update example test

---

.github/workflows/golangci-lint.yml

- Introduced a step to check for changes in Go files using dorny/paths-filter.
- Conditional execution of the linting step based on the presence of Go file changes.
This enhancement optimizes the CI process by only running linting when relevant files are modified, improving efficiency.

feat(github-actions): add Go file change detection to golangci-lint workflow

---

.github/workflows/go.yml

Signed-off-by: Kemal Akkoyun <kemal.akkoyun@datadoghq.com>

chore(ci): Fix flaky tests

---

api/client.go
api/client_test.go

This fixes the issue where the client blocks for the entire duration of the response stream, even when the provided context had already been canceled or times out
Relevant issue #1698

fix: client prompt return on context cancellation

---

exp/api/remote/remote_api.go

Bubble up the write response code instead of hard-coding it to 204. The write response struct by default uses 204, but many rw 1.0 implementations in the wild will be using 2xx. This allows it to be flexible.
cc: @bwplotka

exp/api: Bubble up status code from writeResponse

---

prometheus/collectors/go_collector_go123_test.go
prometheus/collectors/go_collector_go124_test.go
prometheus/go_collector_metrics_go123_test.go
prometheus/go_collector_metrics_go124_test.go

Update runtime metrics for Go v1.23 and v1.24, to include `go_godebug_non_default_behavior_allowmultiplevcs_events_total`.

Update runtime metrics for Go v1.23 and v1.24

---

prometheus/collectors/go_collector_latest.go

This pr repalces the link from src/runtime/metrics/description.go to runtime/metrics package docs. The change is reasonable as:
- go doc has integrated go version switch, but old link cannot change it via web ui.
- the package docs is sufficient to show all provided metrics from runtime, we don't need to see code even it's not complex.
@ArthurSens

prometheus/collectors: use godoc link for runtime/metrics supported metrics

---

exp/api/remote/remote_api.go
exp/api/remote/remote_api_test.go
exp/api/remote/remote_headers.go
exp/api/remote/remote_headers_test.go

* Re store: We don't need to pass context - you have it in http.Request.Context()
* Re rename: Technically we have API and Handler is only for remote write, not read, thus making space for "read" one day.
I also:
*  touched write response: I made read flow private, otherwise it's confusing how to use this structure from outside.
* renamed snappy decoder to SnappyDecodeMiddleware (tighter name)

remote: simplified Store interface; renamed Handler to WriteHandler

---

api/prometheus/v1/api.go
api/prometheus/v1/api_test.go

The changes introduce a new `/format_query` API endpoint to handle query formatting in the Prometheus API.
This includes implementing the `FormatQuery` function in `api.go` and adding corresponding test cases in `api_test.go` to ensure proper functionality.
Fix #1845

feat(api/prometheus): add format_query endpoint for query formatting

---

api/prometheus/v1/api.go

feat(api): add FormatQuery method to Prometheus v1 API

---

go.mod
go.sum

Upgrade to [prometheus/common@v0.66.1](https://github.com/prometheus/common/releases/tag/v0.66.1). This version of prometheus/common just drops the dependencies github.com/grafana/regexp and go.uber.org/atomic and replaces gopkg.in/yaml.v2 with go.yaml.in/yaml/v2 (a drop-in replacement).

[release-1.23] Upgrade to prometheus/common@v0.66.1

---

exp/api/remote/remote_api.go

This PR fixes a typo in the remote api error msg.
`assumining ` to `assuming`

Fix typo in remote api err msg

---

exp/api/remote/remote_api.go

The compressed buffer is released before the request is made, which leads to corrupted remote-write payloads being sent to the target.
The compression function uses the pattern where the destination slice can be passed in, and the function returns a reference to it, adjusted for length.

bug(remote_write): Fix compression buffer pooling

---

exp/api/remote/remote_api.go
exp/api/remote/remote_api_test.go

- Change RetryCallBack to pass in as a params for Write function instead of from API option to be more flexible.

Change RetryCallBack initialized
